### ISSUE TITLE
Show a document on ios with password protection

### ISSUE THREAD

**Issue by lsom11** [PDFTron/pdftron-react-native#11]
When the password option is enabled on android the pdf is shown perfectly, but on ios a blank screen is shown and I'm unable to navigate off the page. It seems like on ios the password parameter isn't received.

![Screen Shot 2019-07-11 at 15 53 42](https://user-images.githubusercontent.com/27585561/61077103-16b7c200-a3f4-11e9-96d2-c09664b97a92.png)

Edit: Just for some more information in development without password protection we can open pdfs without problems.

**Comment by dluco-pdftron** [comment]
Hi @lsom11,
Thank you for letting us know about this issue! Passwords on iOS are now fully supported with commit c68c0658064d81d2a26b8562bbe8530f1e68e538.
Please let us know how this works for you. Thanks again!

**Comment by dluco-pdftron** [comment]
Closing this issue, please re-open if you run into any problems.

**Comment by lsom11** [comment]
It seems we're still having problems opening PDFs in production. I've submitted a PR that I think resolves this problem.
