### ISSUE TITLE
fn.apply is not a function

### ISSUE THREAD

**Issue by divyaponnurucmsedge** [PDFTron/pdftron-react-native#116]
I am getting the below error when integrating the PDFTron/pdftron-react-native into my application .

BUNDLE  ./index.js

error: index.js: fn.apply is not a function.

please help me to solve that issue....

**Comment by divyaponnurucmsedge** [comment]
please help me to solve that issue.

**Comment by sgong-pdftron** [comment]
@divyaponnurucmsedge seems like you are getting problem about React Native that is not related to PDFTron. Maybe you can start with a simpler application, i.e. start with a hello world template provided by the platform first. https://reactnative.dev/docs/environment-setup

**Comment by divyaponnurucmsedge** [comment]
Can we remove any features in pdftron like sharing feature

**Comment by sgong-pdftron** [comment]
@divyaponnurucmsedge yes for sure, you can remove any menu in the main toolbar. Were you able to get your application up and running?

**Comment by divyaponnurucmsedge** [comment]
Yeah....its working fine. I just want to remove sharing feature in that.

**Comment by sgong-pdftron** [comment]
You can use `disabledElements` API to hide `Config.Buttons.shareButton`
https://github.com/PDFTron/pdftron-react-native#disabledelements

**Comment by divyaponnurucmsedge** [comment]
can we edit word document in pdftron.

**Comment by sgong-pdftron** [comment]
@divyaponnurucmsedge it is possible to convert the word document to PDF then edit it with PDFTron.

**Comment by divyaponnurucmsedge** [comment]
can we open html page in pdftron
