### ISSUE TITLE
Does this support react-native-windows?

### ISSUE THREAD

**Issue by soymanuvalle** [PDFTron/pdftron-react-native#137]
Hello, on our company we're currently using the webviewer-ui for the Web and Xamarin for the mobile apps and windows uwp. We're looking to switch to react-native and I was wondering if this package is compatible with https://github.com/microsoft/react-native-windows or if special bindings should be developed to make it work.

Thanks

**Comment by sgong-pdftron** [comment]
@soymanuvalle special binding will be needed for windows module. Currently this library only supports Android and iOS. If you could contact us via https://www.pdftron.com/form/request/ with your current UWP application, we may be able to have better insight to the scope of the UWP react-native project. Thanks!

**Comment by soymanuvalle** [comment]
Thanks for the quick reply! No problem, we'll make the windows apps on electronJS with react and the mobile apps with this react-native package
