### ISSUE TITLE
Unable to build: No visible @interface

### ISSUE THREAD

**Issue by Epick362** [PDFTron/pdftron-react-native#153]
**Describe the bug**
Building on iOS fails with message: 
```
/............/node_modules/react-native-pdftron/ios/DocumentViewController/RNTPTDocumentViewController.m:157:12:` No visible @interface for 'PTDocumentViewController' declares the selector 'pdfViewCtrl:downloadEventType:pageNumber:'
```

When I comment out the line 
```[super pdfViewCtrl:pdfViewCtrl downloadEventType:type pageNumber:pageNum];``` 
in `RNTPTDocumentViewController.m`
**and**
```[super pdfViewCtrl:pdfViewCtrl downloadEventType:type pageNumber:pageNum];``` 
in `RNTPTCollaborationDocumentViewController.m`

the project **builds successfully** so this is a valid workaround.

**Steps to Reproduce the Problem**

1. Add pdftron to project.
2. install pods
3. try to compile iOS
4. Build fails

**Expected behavior**

Build doesn't fail

**Platform/Device Information (please complete the following information if applicable):**
 - Platform: iOS
 - Device: iPhone 11
 - OS: iOS 10.0

**Comment by JamieDass** [comment]
Hi @Epick362,

It sounds like you may be using an older version of the React Native PDFTron wrapper.
Are you able to update to a more recent version of the wrapper and check if the build problem still occurs?

**Comment by Epick362** [comment]
@JamieDass you are right, I didn't notice the PDFNet url in Podfile changed. Thank you for the advice
