### ISSUE TITLE
showLeadingNavButton having no effect

### ISSUE THREAD

**Issue by JeremyBradshaw7** [PDFTron/pdftron-react-native#154]
Following the sample code I'm including these props in my DocumentViewer:

```
      showLeadingNavButton={true}
      leadingNavButtonIcon={Platform.OS === 'ios' ? 'ic_close_black_24px.png' : 'ic_arrow_back_white_24dp'}
```

I'm expecting some back icon to be shown (where should it be? top left?) but nothing is shown (on iOS in dev mode at least). Are we expected to put the image resources somewhere or are they automatically bundled as part of the pdftron package? How would we supply our own? There's nothing in the readme to describe the process.

**Comment by sgong-pdftron** [comment]
@JeremyBradshaw7 yes, you will need to add the icon shown here: https://github.com/PDFTron/pdftron-react-native/tree/master/example/ios. Could you give a try? You can supply any icon and change the code to the actual name accordingly.

We will look into updating the documentation.

**Comment by JeremyBradshaw7** [comment]
> @JeremyBradshaw7 yes, you will need to add the icon shown here: https://github.com/PDFTron/pdftron-react-native/tree/master/example/ios. Could you give a try? You can supply any icon and change the code to the actual name accordingly.
> 
> We will look into updating the documentation.

Thanks. Add it to where though? On android the specified icon just shows without me putting it anywhere, on ios it doesn't. I'm happy to stick with a default icon but just specifying showLeadingNavButton={true} without an icon but that doesn't seem to work either.

**Comment by JeremyBradshaw7** [comment]
Copied it to my ios folder and it still doesn't show for some reason.

**Comment by JamieDass** [comment]
Hi @JeremyBradshaw7,

Apologies for the confusion.
After running `pod install` there should be an `xcworkspace` which contains your app project. You should open that workspace in Xcode and then drag the icons into your app project. The button icon should then appear correctly in your app.
This is how that should look in Xcode:
![RN_icons](https://user-images.githubusercontent.com/20866295/98024329-01bb2b00-1dbd-11eb-9877-01c2d3a74006.png)

We have also updated the project to show a system close icon if no image is found:
[https://github.com/PDFTron/pdftron-react-native/pull/156](https://github.com/PDFTron/pdftron-react-native/pull/156).
The example iOS project also now includes the icons in its asset catalog.

Does that solve the issue for you?

**Comment by JeremyBradshaw7** [comment]
Yes thanks, if no icon is supplied a Cancel link is shown on iOS, is that localisable to 'Back' somehow?

**Comment by JamieDass** [comment]
Hi @JeremyBradshaw7,

Sorry that was a typo in the earlier PR. There should just be an 'X' icon image instead of the `Cancel` text.
This has now been fixed in https://github.com/PDFTron/pdftron-react-native/pull/157.

**Comment by JeremyBradshaw7** [comment]
Excellent thanks, working well.

**Comment by JeremyBradshaw7** [comment]
Unfortunately this has introduced a build issue on Android - see https://github.com/PDFTron/pdftron-react-native/issues/158
