### ISSUE TITLE
Android Status Bar issue

### ISSUE THREAD

**Issue by JeremyBradshaw7** [PDFTron/pdftron-react-native#160]
Any react native page which includes this component seems to force the page up to be rendered underneath the Android status bar, so partly hidden. While `padStatusBar` can be used, this assumes that the pdf is displayed full screen. I'm displaying pdfs under a header and tab control, so when a pdf is rendered without `padStatusBar` it has this effect (the top bit of the header is occluded):

![image](https://user-images.githubusercontent.com/36155348/98529361-6bcc4800-2275-11eb-9dde-56274b46f157.png)

Adding `padStatusBar` only adds padding to the pdf DocumentView control:

![image](https://user-images.githubusercontent.com/36155348/98529486-93231500-2275-11eb-9445-4ab51a5bb042.png)

The only way we can deal with this is to hide the android status bar completely whenever this component is rendered, but that leads to a rather clunky user experience.

**Comment by sgong-pdftron** [comment]
@JeremyBradshaw7 The viewer does not assume location of your view. So in this case, you can use https://reactnative.dev/docs/statusbar to define your layout instead of `padStatusBar` prop. Could you please give a try?

**Comment by JeremyBradshaw7** [comment]
> @JeremyBradshaw7 The viewer does not assume location of your view. So in this case, you can use https://reactnative.dev/docs/statusbar to define your layout instead of `padStatusBar` prop. Could you please give a try?

I'm not sure what you mean. The issue is that the DocumentView control, as soon as it is displayed, has the side-effect on the containing page in that it is losing its top padding that normally forces it to be rendered below the android status bar. The page doesn't know if there is a DocumentView being displayed as that may be buried deep in the subcomponent hierarchy. I do think its a bug that a component has such a side-effect on its containing page.

**Comment by sgong-pdftron** [comment]
@JeremyBradshaw7 is your app in full screen mode? (i.e. hides all system controls?)
Could you send us exact layout so we can try on our end? Thanks.

**Comment by JeremyBradshaw7** [comment]
@sgong-pdftron no it's not, see description, I show it under a header and a tab control, but it should be reproducible on any page where it's not at the top of the screen on android, eg:

```
<View style={{flex: 1}}>
  <Text style={{fontSize: 30}}>Check this is not clipped</Text>
  <DocumentViewer ... />
</View>
```

**Comment by sgong-pdftron** [comment]
![image](https://user-images.githubusercontent.com/20527369/99002622-90345880-24f1-11eb-8516-088e42fe8b39.png)

@JeremyBradshaw7 I'm having some difficulty reproducing on my end. However there is major changes in the viewer in the latest version. Could you update and give another try?

Thanks.

**Comment by JeremyBradshaw7** [comment]
@sgong-pdftron thanks yes version "2.0.3-beta.1" with the new UI doesn't seem to have this issue.
