### ISSUE TITLE
[Tablet IOS] Cannot show bottom tool bar in Tablet IOS

### ISSUE THREAD

**Issue by hoaphantn7604** [PDFTron/pdftron-react-native#173]
![Simulator Screen Shot - iPad Pro (9 7-inch) - 2020-11-26 at 15 14 38](https://user-images.githubusercontent.com/50919571/100324775-458b0400-2ffa-11eb-952f-589c27f5006e.png)

**Comment by JamesTron** [comment]
On tablets, the navigation/search buttons and presets bar are all shown at the top. Only on iPhone is there a bottom bar. So this is as-designed.
