### ISSUE TITLE
[Android] Support React Navigation with React-Native-Screens

### ISSUE THREAD

**Issue by nguyenlinh93x** [PDFTron/pdftron-react-native#18]
Hi team, <br/>
Thanks for your amazing library. <br/>
I have a problem when i use pdftron with react-native-screens. My app crash if i navigate Document View ---> back previous page --> navigate Document.<br>
Currently i must disable react-native-screens to avoid crash. <br>
Below is my crash log and example. Thanks for your support.

[bugsnag.txt](https://github.com/PDFTron/pdftron-react-native/files/3438213/bugsnag.txt)
[react-native-sample-with-screens.zip](https://github.com/PDFTron/pdftron-react-native/files/3438212/react-native-sample-with-screens.zip)

**Comment by sgong-pdftron** [comment]
@nguyenlinh93x 

Running the sample project as is, this is what I see:

![view pdf](https://user-images.githubusercontent.com/20527369/62390826-0dfc6c80-b518-11e9-992e-6bbbf38ea28c.gif)


Could you elaborate on how to reproduce the crash?
Thanks.
