### ISSUE TITLE
npm package not found. 

### ISSUE THREAD

**Issue by aftabaminzoobiapps** [PDFTron/pdftron-react-native#185]
I tried the following commands but n0o one is working. 

> npm install github:PDFTron/pdftron-react-native --save

> npm i react-native-pdftron --save

**Comment by Maxwell-Yang-PDFTron** [comment]
@aftabaminzoobiapps could you please attach the error message? I cannot replicate this problem by using your first command. The [guide](https://github.com/PDFTron/pdftron-react-native) on our repo might provide useful information for you in this scenario.

**Comment by sgong-pdftron** [comment]
No more info obtained, close for now.
