### ISSUE TITLE
https not supported

### ISSUE THREAD

**Issue by daleknauss** [PDFTron/pdftron-react-native#2]
Using DocumentView in iOS and passing in a pdf with https fails with the following error:

Error: Error Domain=PTErrorDomain Code=0 "Unsupported URL scheme" UserInfo={NSURL=https://<DOCUMENT_PATH>.pdf, NSLocalizedDescription=Unsupported URL scheme, NSLocalizedFailureReason=Cannot open URL with scheme "https"}

That same document served with http works every time.

**Comment by sgong-pdftron** [comment]
@daleknauss 
Can you please try updating your cocoapod for PDFTron?
If you have latest in Pod file, then run `pod update`.

HTTPS issue is fixed in latest version of PDFTron iOS SDK.

Sorry for the delayed response.

**Comment by sgong-pdftron** [comment]
Closed as issue should be resolved. Re-open if the issue still persist. Thanks.
