### ISSUE TITLE
App crashes on android 9

### ISSUE THREAD

**Issue by grin4ello2** [PDFTron/pdftron-react-native#205]
**Describe the bug**
When you create screen with **DocumentView** - app will crash after you try to load that screen. Same result for files loaded from storage or from remote url.
Works fine for android 10 OS.

**Steps to Reproduce the Problem**
1. Install latest version of react native PDFTron on android 9
2. Open screen with **DocumentView** component
3. Allow access to storage if necessary.
4. App will crash.

**Expected behavior**
You can view and edit file.

**Platform/Device Information (please complete the following information if applicable):**
 - Platform: Android 9
 - Device: Galaxy S8, Xiaomi Redmi Note 7

**Additional context**
Stack traces
androidx.core.util.Preconditions.checkNotNull Preconditions.java:119
androidx.core.view.WindowInsetsCompat.toWindowInsetsCompat WindowInsetsCompat.java:169
androidx.core.view.ViewCompat$Api21Impl$1.onApplyWindowInsets ViewCompat.java:4753
android.view.DispatchFairInsetsFrameLayout.applyWindowInsets DispatchFairInsetsFrameLayout.java:135
android.view.DispatchFairInsetsFrameLayout.dispatchApplyWindowInsets DispatchFairInsetsFrameLayout.java:114
android.view.DispatchFairInsetsFrameLayout.dispatchApplyWindowInsets DispatchFairInsetsFrameLayout.java:119

**Comment by Maxwell-Yang-PDFTron** [comment]
Hello grin4ello2! Unfortunately, I could not seem to reproduce this bug, on an Android 9 (Pie) simulator. If possible, could you please provide the react native code you used to produce this bug? Thank you!

**Comment by grin4ello2** [comment]
https://gist.github.com/grin4ello2/7c445af114f5e2effb133e49a15637a8

**Comment by Maxwell-Yang-PDFTron** [comment]
Sorry, your example involves the use of some other parts of a project, so I would not be able to use easily. If possible, could you run this repo in your Android 9 device, and see if anything breaks? Thank you! https://github.com/PDFTron/react-native-sample

**Comment by grin4ello2** [comment]
It’s work for me with https://github.com/PDFTron/react-native-sample <https://github.com/PDFTron/react-native-sample>. Will try to find out whats wrong on my project.

**Comment by grin4ello2** [comment]
@Maxwell-Yang-PDFTron 
yarn insall installing PdfTron for android with 
dependencies {
    implementation "com.facebook.react:react-native:+"

    implementation "com.pdftron:pdftron:7.1.5"
    implementation "com.pdftron:tools:7.1.5"
    implementation "com.pdftron:collab:7.1.5"
}
and npm install installing 
dependencies {
    implementation "com.facebook.react:react-native:+"

    implementation "com.pdftron:pdftron:8.1.1-beta07"
    implementation "com.pdftron:tools:8.1.1-beta07"
    implementation "com.pdftron:collab:8.1.1-beta07"
}

com.pdftron:pdftron:7.1.5 - got bug that I described.

**Comment by sgong-pdftron** [comment]
@grin4ello2 Could you please updated to the latest version of Android. Older versions are no longer supported for React Native. Does 8.1.1-beta07 work for you? Thanks.

**Comment by grin4ello2** [comment]
Already updated. You can close issue, thanks.
