### ISSUE TITLE
Lack of documentation

### ISSUE THREAD

**Issue by Frekansapp** [PDFTron/pdftron-react-native#206]
Hi, i'm trying to implement pdfTron into my RN project but i can't find what i'm searching.
There is no code example about how can i add custom header or how can i use other pdftron's API.

What is the working logic of autosave? What i'm trying to basicly reupload changed document to my server. Can i add custom button to ui and save document to my server. I need code examples. Could you please share.

Thanks. Best regrards.

**Comment by Maxwell-Yang-PDFTron** [comment]
Hi Frekansapp, I am sorry to hear that you are having trouble using our API. We are working on a refinement of the API page, but all of the entries should have a small code example attached to them currently on master by now (https://github.com/PDFTron/pdftron-react-native/blob/master/README.md), including [customHeaders](https://github.com/PDFTron/pdftron-react-native/blob/master/README.md#customheaders).

Autosave saves document periodically and on exiting the viewer. For your use case, I would suggest looking into [saveDocument](https://github.com/PDFTron/pdftron-react-native/blob/master/README.md#savedocument) and [onLeadingNavButtonPressed](https://github.com/PDFTron/pdftron-react-native/blob/master/README.md#onleadingnavbuttonpressed). When the leading navigation button is pressed, you can call saveDocument, which would provide the path to the saved document. You can then upload to server using this path (not with our API for this step).

For a bigger example, we have [react-native-sample](https://github.com/PDFTron/react-native-sample) if you are interested.

Hope that helps. Thank you.

**Comment by Frekansapp** [comment]
> onLeadingNavButtonPressed

Hi, thanks for answer. Can i add new NavButton? Actualy i didn't understand what is the navbutton is it bottom nav buttons? Could you please share image? Can i add a button on bottom tab?

**Comment by Maxwell-Yang-PDFTron** [comment]
Hello Frekansapp, the leadingNavButton is circled in the screenshot I have attached. We currently only allow users to make change to this button. If you wish to add a button to the bottom, I would suggest hiding our bottom toolbar through [bottomToolbarEnabled](https://github.com/PDFTron/pdftron-react-native#bottomtoolbarenabled) and build your custom toolbar in React Native.

![Simulator Screen Shot - iPod touch (7th generation) - 2021-01-28 at 12 13 56](https://user-images.githubusercontent.com/70409796/106194052-2ed06d00-6163-11eb-90e1-4c4f35579c1e.png)

**Comment by Frekansapp** [comment]
@Maxwell-Yang-PDFTron Thanks for your answer it's help too much. I found a bug i will open a new issue
