### ISSUE TITLE
Possible memory leak in RNTPTDocumentView (iOS)

### ISSUE THREAD

**Issue by timkomip** [PDFTron/pdftron-react-native#21]
While using this library I noticed memory usage climbing and not falling. I navigated to the page with the `DocumentView` and navigated back. Did this 4 times and recorded memory usage.

![image](https://user-images.githubusercontent.com/3844352/63281253-491dd000-c27a-11e9-94ae-e5d87e6f97ad.png)

I used Instruments to determine which objects where retained and found:
![image](https://user-images.githubusercontent.com/3844352/63280811-7ddd5780-c279-11e9-9274-1814202031e6.png)
So I navigated to the source code and found the following line.
https://github.com/PDFTron/pdftron-react-native/blob/ecf52fe5b1c893888e8d71cfa59d8058c0a269df/ios/RNTPTDocumentView.m#L134-L138
The navigation view controller is being added as a child to the parent every time `didMoveToWindow` is called but is never being removed (and the parent is not going away either)
With the debugger on, you can see that the child count keeps growing:
![image](https://user-images.githubusercontent.com/3844352/63281145-15db4100-c27a-11e9-9ac8-aa291c07a28c.png)

Not sure what the best fix is. Perhaps reusing the view controller instance? Or removing it when the component goes away?

I have not checked Android but since this deals with the core UIKit classes and stuff, I figure this is probably only in iOS.

**Comment by dluco-pdftron** [comment]
Hi Michael,
Thanks for letting us know about this issue!
The memory leak should be fixed now with the latest commit https://github.com/PDFTron/pdftron-react-native/commit/747a0f251aa21a25b6838efdd3e8bfa7a42cdb2b.
Thanks again! Please let us know if you encounter any other issues.
