### ISSUE TITLE
saveDocument method returns wrong file.

### ISSUE THREAD

**Issue by grin4ello2** [PDFTron/pdftron-react-native#210]
**Describe the bug**
When working with images on latest version of Pdftron(Android), after making changes - saveDocument method returns image file without changes. 

**Steps to Reproduce the Problem**
1. Open image file
2. Add changes to file
3. Call saveDocument method
4. Promise returns with image file without any changes

**Expected behavior**
On previous version and on iOS version of your app saveDocument method was returning pdf file with all changes been made.

**Platform/Device Information (please complete the following information if applicable):**
 - Platform:Android
 - Device: Pixel 2, Pixel 3 XL
 - OS: Android 10 and Android 9
 - Pdftron android version: 8.1.1

**Comment by sgong-pdftron** [comment]
@grin4ello2 this issue is resolved by https://github.com/PDFTron/pdftron-react-native/pull/211.
Could you please update and try again? Thanks.

**Comment by grin4ello2** [comment]
Returns pdf file now, thanks for quick fix.

**Comment by grin4ello2** [comment]
@sgong-pdftron saveDocument returns file without changes.
