### ISSUE TITLE
saveDocument method returns wrong file without changes.

### ISSUE THREAD

**Issue by grin4ello2** [PDFTron/pdftron-react-native#212]
Describe the bug
When working with images on latest version of Pdftron(Android), after making changes - saveDocument method returns pdf file without changes.

Steps to Reproduce the Problem

Open image file
Add changes to file
Call saveDocument method
Promise returns with pdf file without any changes
Expected behavior
On previous version and on iOS version of your app saveDocument method was returning pdf file with all changes been made.

Platform/Device Information (please complete the following information if applicable):

Platform:Android
Device: Pixel 2, Pixel 3 XL
OS: Android 10 and Android 9
Pdftron android version: 8.1.1

**Comment by sgong-pdftron** [comment]
@grin4ello2 I'm able to reproduce the problem. Will update you asap.

Thanks.

**Comment by Frekansapp** [comment]
I had it same problem and i changed the pdf path like this  const path = `${metrics.URL}/${props.item.url.replace(/[\\]/g, '/')}`
and it's worked for me. Maybe it's help.

**Comment by sgong-pdftron** [comment]
We will have a fix pushed either today or early next week. Thanks.

**Comment by sgong-pdftron** [comment]
@grin4ello2 This issue is now resolved in latest master. Could you update and try again? Thanks.

**Comment by grin4ello2** [comment]
It’s work fine for me. Thanks for fix.
