### ISSUE TITLE
File Names Containing Space

### ISSUE THREAD

**Issue by Frekansapp** [PDFTron/pdftron-react-native#214]
Hello,

We cannot open the pdf files whose urls contain space in the file name. We get a warning message "error opening file".

Could you please help us in solving the problem?

Thank  you in advance.

**Comment by sgong-pdftron** [comment]
@Frekansapp would you be able to send us a example for testing? Thanks.

**Comment by Frekansapp** [comment]
> @Frekansapp would you be able to send us a example for testing? Thanks.

I tried on your example project

**Comment by sgong-pdftron** [comment]
@Frekansapp I mean an example URL?

**Comment by sgong-pdftron** [comment]
Also typically you won't have space in URL, you will need to encode the URL to include special character that represent the empty space, a typical example would be: https://pdftron.s3.amazonaws.com/custom/downloadertest/sg/test%20js.pdf

**Comment by Frekansapp** [comment]
`https://testapi.denetmen.app/uploads/MuglaAltin/1756264/pdf/54895310504497_PDFTRON MOBİLE_about.pdf`
https://testapi.denetmen.app/uploads/MuglaAltin/1756264/pdf/54895310504497_PDFTRON%20MOB%C4%B0LE_about.pdf

Yes, i know that but browser's can handle, why pdfTron wouldn't. I'have 5000+ document if pdfTron can't open them i have to change it all.

**Comment by sgong-pdftron** [comment]
@Frekansapp thanks for the example, sure we could encode on our end.
May I ask if you are having this issue on both platforms or just one, if so, which? Thanks.

**Comment by Frekansapp** [comment]
> @Frekansapp thanks for the example, sure we could encode on our end.
> May I ask if you are having this issue on both platforms or just one, if so, which? Thanks.


I did not have a chance to try ios. I just tried it for Android.

**Comment by sgong-pdftron** [comment]
@Frekansapp this should be resolved in latest master, could you update and try again, thanks.
