### ISSUE TITLE
Clicking undo in the Android app on the Mark up does not delete everything then the app closes and a random app opens

### ISSUE THREAD

**Issue by grin4ello2** [PDFTron/pdftron-react-native#217]
**Steps to Reproduce the Problem**
https://user-images.githubusercontent.com/61944382/108502201-7a3ded00-72c3-11eb-8718-d3075efc313d.mp4

**Platform/Device Information (please complete the following information if applicable):**
 - Platform: Android
 - Device: Samsung Galaxy S8
 - OS: Android 10

**Comment by sgong-pdftron** [comment]
@grin4ello2 could you send us this exact file shown in the video so we could try on our end? Thanks.

**Comment by grin4ello2** [comment]
That was just a photo make from same phone. 

> 19 февр. 2021 г., в 18:52, sgong-pdftron <notifications@github.com> написал(а):
> 
> @grin4ello2 <https://github.com/grin4ello2> could you send us this exact file shown in the video so we could try on our end? Thanks.

**Comment by sgong-pdftron** [comment]
@grin4ello2 the reason I'm asking is i'm having trouble reproducing on my end:

![ezgif-2-911d5a87c845](https://user-images.githubusercontent.com/20527369/108547928-fb838880-729f-11eb-859b-e7f59fd8e96b.gif)

Any help is appreciated. Thanks.

**Comment by sgong-pdftron** [comment]
No more info obtained, closed for now.
