### ISSUE TITLE
saveDocument method returns wrong file without changes

### ISSUE THREAD

**Issue by grin4ello2** [PDFTron/pdftron-react-native#218]
**Describe the bug**
When working with images on latest version of Pdftron(iOS), after making changes - saveDocument method returns pdf file without changes. It was fine 11 days ago when I was posting same Bug for Android.

**Steps to Reproduce the Problem**

Open image file
Add changes to file
Call saveDocument method
Promise returns with pdf file without any changes
Expected behavior
On previous version and on iOS version of your app saveDocument method was returning pdf file with all changes been made.

**Platform/Device Information (please complete the following information if applicable):**

Platform:iOS
Device: iPhone 11
OS: iOS

**Comment by Maxwell-Yang-PDFTron** [comment]
Hello grin4ello2, unfortunately I cannot reproduce this bug on my end.

I tried to reproduce using the following steps:
- Use the example app in React Native, but with slight modification (change path to an image, and call saveDocument when onLeadingNavButtonPressed is activated)
- Add some annotations to the image, and click on the "X" icon (leading navigation button).
- Use the path from saveDocument, and find that annotations have been added to the saved pdf file

Here are some infos:
Platform: iOS 11.0
Device: iPhone 11 (Simulator)
React Native: 16.3.1
PDFNet: http://www.pdftron.com/downloads/ios/cocoapods/pdfnet/latest.podspec

For your information, there is no change to saveDocument in our wrapper recently. If you believe there is a mistake in the wrapper, please provide some more details to help us reproduce and locate the issue. Thank you.

**Comment by Maxwell-Yang-PDFTron** [comment]
As a follow-up, you could also use this branch: https://github.com/PDFTron/pdftron-react-native/tree/saveImageDemo. The only change is mentioned in the steps of the previous comment.

**Comment by grin4ello2** [comment]
> * Use the example app in pdftron-react-native repo, but with slight modification (change path to an image, and call saveDocument when onLeadingNavButtonPressed is activated)
> * Add some annotations to the image, and click on the "X" icon (leading navigation button).
> * Use the path from saveDocument, and find that annotations have been added to the saved pdf file

Try that steps without pressing "X" icon after adding. You will see your annotations on screen, but onAnnotactionChange method won't fire. If you call saveDocument file will save without changes. User should always press "X" before saving document?

**Comment by grin4ello2** [comment]
Also some annotations don’t have that X  image

**Comment by Maxwell-Yang-PDFTron** [comment]
Hi grin4ello2, the "X" I was referring to is not associated with any annotation, but rather the leading navigation button, aka this highlighted button:
![Simulator Screen Shot - iPod touch (7th generation) - 2021-02-22 at 09 14 39](https://user-images.githubusercontent.com/70409796/108744487-d46ec600-74ee-11eb-873d-83b75baead8a.png)

Users would not need to press anything manually, I just defined the callback for that button onLeadingNavButtonPressed (https://github.com/PDFTron/pdftron-react-native/blob/master/API.md#onleadingnavbuttonpressed) to call saveDocument for demonstration. You could customize when you would like to call saveDocument.

onAnnotationChanged will fire regardless of clicking "X", since annotations changes could happen without saving to local file system. Again, if you need help, feel free to provide more information about your problem, thanks.

**Comment by grin4ello2** [comment]
https://user-images.githubusercontent.com/61944382/109140892-240ef500-776e-11eb-9d3f-6d909f2fcf23.mov

I think I found the problem. onAnnotationChanged doesn't fire when we add some of annotations.

**Comment by Maxwell-Yang-PDFTron** [comment]
Hi grin4ello2, currently pencil kit and ink tool do not fire the onAnnotationChanged event until it is unselected from the toolbar. At around 0:16 - 0:19 of your video, you selected the freehand tool (so pencil kit is unselected), which called onAnnotationChanged and onExportAnnotationCommand event (so you could see something printed on your terminal).

**Comment by grin4ello2** [comment]
currently pencil kit and ink tool do not fire the onAnnotationChanged event until it is unselected from the toolbar

Do you have any plans to fix it in near future?

**Comment by Maxwell-Yang-PDFTron** [comment]
@grin4ello2 ink tool is likely to be updated soon, bu not for pencil kit for some file size reasons.
