### ISSUE TITLE
build  error

### ISSUE THREAD

**Issue by canyuegongzi** [PDFTron/pdftron-react-native#219]
* What went wrong:
Could not determine the dependencies of task ':app:mergeDebugAssets'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.pdftron:pdftron:8.1.2-beta05.
     Searched in the following locations:

**Comment by Maxwell-Yang-PDFTron** [comment]
Hi canyuegongzi. Unfortunately, I failed to reproduce this bug. Could you confirm that you have followed all the steps here (https://github.com/PDFTron/pdftron-react-native#installation)? Or try to run the demo in our repo (in the example folder) and see if the problem exists. If the issue persists, feel free to add a follow-up comment and provide the detailed steps to reproduce it. Thank you!

**Comment by sgong-pdftron** [comment]
No more info obtained, will close for now.
