### ISSUE TITLE
[HELP] "FloatingView" with react-native. How to render components fixed to pages

### ISSUE THREAD

**Issue by soymanuvalle** [PDFTron/pdftron-react-native#225]
Hello. I'm trying to render custom components over pages and get them fixed to the scrolling position while moving around the PDFTron viewer ScrollView. On the webviewer I've done it modifying the elements of the iframe with js, on the mobile apps I've found that this has to be made with a [UIView](https://www.pdftron.com/documentation/ios/guides/advanced/adding-a-uiview-to-a-pdf-page/), however, it looks like the bindings hasn't been developed for react-native yet.

Could you give me some orientation of how this should be done please, any information would be very useful.
![image](https://user-images.githubusercontent.com/9582420/110560208-5af8e980-8124-11eb-9d2a-d3ab6e103613.png)
Similar to the photo from the docs example, I need to draw over the pages but instead of rendering those rectangles I would need to render custom react components.

The company I work for has a Support subscription with PDFTron if that helps on something.
If you need anything else from my side let me know.

Thank you very much

**Comment by soymanuvalle** [comment]
@sgong-pdftron Thanks, I've tried with that but I didn't figure out how to attach the components to the page position while scrolling. I've been able to draw a rectangle with native code forking the repo
![image](https://user-images.githubusercontent.com/9582420/110661423-51629680-81a3-11eb-866d-224ec0de6568.png)
It works fine but now I would have to figure out how to pass react components inside that view...

> If you want to place UI on top of PDFTron viewer in React Native, the best approach would be using React Native components.
How could I position the react native components based on the scrollview of the pdftron viewer? Is there a way to access the pdfViewCtrl scroll callbacks like GetHScrollPos and GetVScrollPos? Because I guess doing what you said would be much easier.

Thanks

**Comment by soymanuvalle** [comment]
> @soymanuvalle scroll position is actually being added in a PR:
> #208
> 
> Could you give that branch a run? and see if that works for you?
> 
> Ideally we want to have enough API so you can achieve this on React Native. And we can work with you to achieve that.

Awesome thanks. I'll give it a try and I'll let you know

**Comment by sgong-pdftron** [comment]
> with native code I can add a subview to the pdfViewCtrl.overlayView so the rectangle is stuck and also it's rendered under the toolbar layout. How could I achieve this with react native components?

Could you post a screenshot of what the current behaviour is and what the expected behaviour is?

> onLayoutChange
can add, @Maxwell-Yang-PDFTron will follow up with PR for that

**Comment by soymanuvalle** [comment]
@sgong-pdftron 
> Could you post a screenshot of what the current behaviour is and what the expected behaviour is?

This is the current behaviour with React Native Components.

https://user-images.githubusercontent.com/9582420/110682555-d48ee700-81b9-11eb-9d49-1ac837ea7da9.mov

The code from the video above is actually a View with absolute position which is rendered above the DocumentView component:
```jsx
<View style={{
  width: 20,
  height: 20,
  top: 0,
  left: 0,
  zIndex: 1,
  position: 'absolute',
  backgroundColor: 'red'
}}/>
```

And this is what I'm trying to do:

https://user-images.githubusercontent.com/9582420/110683479-d5744880-81ba-11eb-8f7c-fcd7e903635e.mov

My objective is to render a component of the same dimensions of a page and attach it to that page number, which would end in something like this:

https://user-images.githubusercontent.com/9582420/110682651-eec8c500-81b9-11eb-95cd-d64ed32483a3.mov

The code of the video above is based on your iOS example of how to "[Add a UIView to a PDF page](https://www.pdftron.com/documentation/ios/guides/advanced/adding-a-uiview-to-a-pdf-page/)". And you can find below the obj-c modifications I've made over a fork of this repository:
```obj-c
// This is executed when the document finishes loading
NSDictionary<NSString *, NSNumber *> *cropBox = [self getPageCropBox:1];
double pageWidth = [cropBox[@"width"] doubleValue];
double pageHeight = [cropBox[@"height"] doubleValue];
RCTLog(@"Test: %@", cropBox);

RNTPTEnrichmentView* redRect = [[RNTPTEnrichmentView alloc] init];
[redRect setBackgroundColor:[UIColor colorWithRed:1 green:0 blue:0 alpha:0.5]];
redRect.pageNumber = 1;
redRect.pdfPageRect = [[PTPDFRect alloc] initWithX1:0 y1:0 x2:pageWidth y2:pageHeight];

[self.currentDocumentViewController.pdfViewCtrl.overlayView addSubview:redRect];

[self positionEnrichmentsViews];

// Other callbacks
- (void)rnt_documentViewControllerDidEndZooming:(PTDocumentBaseViewController *)documentViewController
{
//    PTPDFViewCtrl *pdfViewCtrl = documentViewController.pdfViewCtrl;
    [self positionEnrichmentsViews];
}

- (void)rnt_documentViewControllerLayoutChanged:(PTDocumentBaseViewController *)documentViewController
{
//    PTPDFViewCtrl *pdfViewCtrl = documentViewController.pdfViewCtrl;
    [self positionEnrichmentsViews];
}

- (void)positionEnrichmentsViews
{
    for(RNTPTEnrichmentView* overlayView in self.currentDocumentViewController.pdfViewCtrl.overlayView.subviews)
    {
        // make sure this is a floating view
        if( [overlayView isMemberOfClass:[RNTPTEnrichmentView class]])
        {
            BOOL pageHidden = NO;
            if( ![self.currentDocumentViewController.pdfViewCtrl pagePresentationModeIsContinuous] )
            {
                pageHidden = ![self.currentDocumentViewController.pdfViewCtrl pageIsOnScreen:overlayView.pageNumber];
            }
            overlayView.hidden = pageHidden;
            CGRect screenRect = [self.currentDocumentViewController.pdfViewCtrl PDFRectPage2CGRectScreen:overlayView.pdfPageRect PageNumber:overlayView.pageNumber];
            screenRect.origin.x += [self.currentDocumentViewController.pdfViewCtrl GetHScrollPos];
            screenRect.origin.y += [self.currentDocumentViewController.pdfViewCtrl GetVScrollPos];
            overlayView.frame = screenRect;
        }
    }
}
```
Another problem of the native approach is that I don't know how I could render React Native Components inside that rectangle or UiView (I haven't tried it yet). But the best solution would be to do it without touching the native code as you said.

And this is the final result of how it looks like on our working web version:

https://user-images.githubusercontent.com/9582420/110684811-597b0000-81bc-11eb-865d-650b4f5020a1.mov



> can add, @Maxwell-Yang-PDFTron will follow up with PR for that

Brilliant, thanks

**Comment by sgong-pdftron** [comment]
@soymanuvalle purely based on the end video that you are trying to achieve, it seems like adding image stamps and you handle the click events yourself may be the easiest way. Basically each of those element will be an image stamp annotation added on the document, they can each have an id and you can decide what to do with it when you click on it. How does that sound?

**Comment by soymanuvalle** [comment]
> @soymanuvalle purely based on the end video that you are trying to achieve, it seems like adding image stamps and you handle the click events yourself may be the easiest way. Basically each of those element will be an image stamp annotation added on the document, they can each have an id and you can decide what to do with it when you click on it. How does that sound?

No that wouldn't work out as some of the components are displayed inline (not in a modal but over the actual page), and those could be videos, carousels, etc.

**Comment by sgong-pdftron** [comment]
In that case you will have to sync with the scroll/layout events. Position the view under the toolbar, we could probably provide the height of the bar.

**Comment by soymanuvalle** [comment]
Is it possible to add an event such as onScroll or something like that in which I could receive the scrollview positions?

**Comment by Maxwell-Yang-PDFTron** [comment]
onLayoutChanged PR: https://github.com/PDFTron/pdftron-react-native/pull/227

**Comment by Maxwell-Yang-PDFTron** [comment]
You might find this PR helpful too: https://github.com/PDFTron/pdftron-react-native/pull/229. It has onScrollChanged event + coordinate conversion functions.

**Comment by soymanuvalle** [comment]
> You might find this PR helpful too: #229. It has onScrollChanged event + coordinate conversion functions.

That's great thanks

**Comment by sgong-pdftron** [comment]
@soymanuvalle Just wanted to let you know that I've had a discussion with the team, we believe it might be unlikely that you could get the performance you want by attaching the view in react native, as there is a lot of scroll/zoom event that you will need to follow up. But do let us know if it works out for you. Thanks!

**Comment by soymanuvalle** [comment]
@sgong-pdftron Thanks for the update. I've been able to render React Native components as subviews of the Native UIView floating view, however I'm still not totally happy about it so I'm trying a different approach with the onScrollChanged event and other callbacks.

I will write again here when I get more updates about the progress.

Thanks

**Comment by soymanuvalle** [comment]
@sgong-pdftron @Maxwell-Yang-PDFTron After spending a few hours trying different attempts I finally ended up passing the JSON data to the native DocumentView component and rendering the "floating" components entirely native. It was the most optimized way, passing react components as children was taking too much RAM.

Although I will render the modal on react, sending an event from the native code to react-native.

Thanks for the help anyway

![image](https://user-images.githubusercontent.com/9582420/111210958-9ffd9f80-85ac-11eb-95e4-5df153700bf5.png)
