### ISSUE TITLE
question about sticky note tool

### ISSUE THREAD

**Issue by 3imed-jaberi** [PDFTron/pdftron-react-native#228]
How I can customize the user interface of the sticky note tool ?

I want to add some things like forms fields (inputs, buttons to send data or navigate to camera screen, import files/images ...etc).

![image](https://user-images.githubusercontent.com/43971542/110869408-ac42dd80-82ca-11eb-904a-9e7ed18e8571.png)

**Comment by sgong-pdftron** [comment]
@3imed-jaberi what you mocked up is very custom, so you will have to build that yourself. I would recommend building it in React Native and handle the tap event of the sticky note annotation. But by PDF spec the content needs to be plain text. How are you planning to include the extra information to the annotation?

**Comment by 3imed-jaberi** [comment]
@sgong-pdftron, thank you for fast reply <3. I'm not sure yet. I still try to discover the SDK for my next project. Maybe I will be saving the information with the same annotation id or something like that ...

You recommend to use something like this:
```javascript
<DocumentView
  onBehaviorActivated = {({action, data}) => {
    console.log('Activated action is', action);
    if (action === Config.Buttons.stickyToolButton) {
      // redirect to other screen wich have form and everything I want !
    }
  }}
/>
```

**Comment by 3imed-jaberi** [comment]
How I can block the popup ?!

My Current Code:

```javascript
 <DocumentView
      document={document}
      showLeadingNavButton={true}
      leadingNavButtonIcon={
        Platform.OS === 'ios'
          ? 'ic_close_black_24px.png'
          : 'ic_arrow_back_white_24dp'
      }
      onLeadingNavButtonPressed={() => navigation.goBack()}
      onExportAnnotationCommand={({ action, xfdfCommand }) => {
        if (action !== 'delete') {
          navigation.navigate('FormScreen')
        }
      }}
    />
```

Current Result:  

![demo](https://user-images.githubusercontent.com/43971542/110992088-bc63c700-8375-11eb-97c9-46c0e8548124.gif)

Also kindly, can I edit xfdfCommand directly beceause I'm thinking of save the information form as string inside the content tag of xfdfCommand ..
```xml
 <?xml version="1.0" encoding="UTF-8"?>
<xfdf xmlns="http://ns.adobe.com/xfdf/" xml:space="preserve">
        <add />
        <modify>
                <text color="#E44234" opacity="1" creationdate="D:20210312200840Z" flags="print,nozoom,norotate" date="D:20210312201008Z" name="d776c722-ddd4-4c64-b1ee-7382f966171f" icon="LocationPin" page="8" rect="205.984,591.567,225.984,611.567" title="">
                        <popup date="D:20210312200840Z" page="8" rect="225.984,611.567,295.984,681.567" />
                        <contents>
                                                /****************************************/
                                                /******* Here I add my form data *****/
                                                /****************************************/
                        </contents>
                        <apref y="611.567" x="205.984" gennum="0" objnum="928" />
                </text>
        </modify>
        <delete />
        <pdf-info import-version="3" version="2" xmlns="http://www.pdftron.com/pdfinfo" />
</xfdf>
```

**Comment by sgong-pdftron** [comment]
@3imed-jaberi to clarify, what you would like to do is when you tap the screen with the sticky note selected, you'll want to show your own dialog?

**Comment by 3imed-jaberi** [comment]
> @3imed-jaberi to clarify, what you would like to do is when you tap the screen with the sticky note selected, you'll want to show your own dialog?

Yes exactly

**Comment by sgong-pdftron** [comment]
We will need to add supporting API for this, we will update here when that's ready

**Comment by Maxwell-Yang-PDFTron** [comment]
@3imed-jaberi master should have what you need by now: use [overrideBehavior](https://github.com/PDFTron/pdftron-react-native/blob/master/API.md#overridebehavior) to disable the popup of sticky note, then either [onBehaviorActivated](https://github.com/PDFTron/pdftron-react-native/blob/master/API.md#onbehavioractivated) or [onAnnotationsSelected](https://github.com/PDFTron/pdftron-react-native/blob/master/API.md#onannotationsselected) event could be used to listen for when sticky note is selected.

**Comment by 3imed-jaberi** [comment]
@Maxwell-Yang-PDFTron @sgong-pdftron , thank you for your quick interaction.
I will check the new features and give you my feedback.

**Comment by 3imed-jaberi** [comment]
@sgong-pdftron @Maxwell-Yang-PDFTron, the 2 methods (`onBehaviorActivated` and `onAnnotationsSelected `)  don't listen to the `overrideBehavior`. Otherwise the `onExportAnnotationCommand` method still listen when I drag and drop or modify the place of the sticky note but I expect to listen also when I click or double click over the icon of the sticky note.

**Comment by Maxwell-Yang-PDFTron** [comment]
@3imed-jaberi onBehaviorActivated would only be called if the action (in this case, disable sticky-note pop-up) is passed in overrideBehavior, and onAnnotationsSelected would be called whenever any annotation is selected.

I have updated the code a bit, so now it should be listening correctly. However, these functions could be called more than once on Android for now, even if you only select the sticky-note once. So you might want to add some handling logic in js. Could you use the latest master and give it another try? Thank you!

**Comment by 3imed-jaberi** [comment]
@Maxwell-Yang-PDFTron, thank you for your effort. 
As you say, these functions could be called more than once on Android. And I noticed that I lose all the sticky notes other than the last one (this had not happened previously).

![lost-sticky-notes-demo](https://user-images.githubusercontent.com/43971542/112563940-978e3b80-8dda-11eb-8443-597a791cf9db.gif)

**Comment by sgong-pdftron** [comment]
@3imed-jaberi would it be possible if you could share a project where we can reproduce this on our end? Thanks!

**Comment by 3imed-jaberi** [comment]
@sgong-pdftron, of course welcome,  I was added U and @Maxwell-Yang-PDFTron. [link](https://github.com/3imed-jaberi/pdf-annotation-prototype)

**Comment by Maxwell-Yang-PDFTron** [comment]
Hi @3imed-jaberi, after checking your repo, it seems you are calling importAnnotation with an xfdfCommand, which is not a correct way.

- importAnnotations takes in an xfdf string, representing the annotations to be added to the document
- importAnnotationCommand takes in an xfdf string too, but this represents the actions / commands to be made to the document

For example, this is an xfdf string for importAnnotations (you could get it through exportAnnotations):

``<?xml version="1.0" encoding="UTF-8"?>\n<xfdf xmlns="http://ns.adobe.com/xfdf/" xml:space="preserve">\n\t<annots>\n\t\t<circle style="solid" width="5" color="#E44234" opacity="1" creationdate="D:20190729202215Z" flags="print" date="D:20190729202215Z" page="0" rect="138.824,653.226,236.28,725.159" title="" /></annots>\n\t<pages>\n\t\t<defmtx matrix="1.333333,0.000000,0.000000,-1.333333,0.000000,1056.000000" />\n\t</pages>\n\t<pdf-info version="2" xmlns="http://www.pdftron.com/pdfinfo" />\n</xfdf>``

Below is an xfdf (command) string for importAnnotationCommand:

``xfdfCommand <?xml version="1.0" encoding="UTF-8"?><xfdf xmlns="http://ns.adobe.com/xfdf/" xml:space="preserve"><add><circle style="solid" width="5" color="#E44234" opacity="1" creationdate="D:20201218025606Z" flags="print" date="D:20201218025606Z" name="9d0f2d63-a0cc-4f06-b786-58178c4bd2b1" page="0" rect="56.4793,584.496,208.849,739.369" title="PDF" /></add><modify /><delete /><pdf-info import-version="3" version="2" xmlns="http://www.pdftron.com/pdfinfo" /></xfdf>``

Notice how the first example only has information about some annotations (to be imported / added), while the second one also specifies whether it is an add, modify or delete, which are all the possible actions that could be applied to the document.

The thing I noticed is that the useEffect of your DocumentViewer.js is calling importAnnotation with a xfdfCommand from your FormScreen.js. Updating this works for me. You might also want to look into other places that use xfdf.

Hope this helps. Thanks.

**Comment by 3imed-jaberi** [comment]
Thank u @Maxwell-Yang-PDFTron, but I use `importAnnotationCommand` with my xfdfCommand and yours also but always tell me that I have an error `[Error: XML Parsing error]` ..

**Comment by Maxwell-Yang-PDFTron** [comment]
Sorry @3imed-jaberi for the late reply. Looking at your project, exportAnnotations is actually not a good function to use in your case, since this would have all annotations returned, which could potentially contain multiple sticky notes. Currently on master, [setPropertiesForAnnotation](https://github.com/PDFTron/pdftron-react-native/blob/master/API.md#setpropertiesforannotation) supports adding propertymap to an annotation. You could utilize this to set custom data (from your form) to the sticky note annotation if required. This function requires an annotation id, which could be obtained by [onBehaviorActivated](https://github.com/PDFTron/pdftron-react-native/blob/master/API.md#onBehaviorActivated), similar to what you have done before. Please comment below if there are more questions, thanks!

**Comment by 3imed-jaberi** [comment]
Thank u @Maxwell-Yang-PDFTron  for following.. 
The behavior problem suggested by `setPropertiesForAnnotation` is that the icon size is too large which affects finding the real location-pin icon location.

Note: only the real icon position is clickable.

- Screenshots: 

![171415745_857118218478677_3474343779610990924_n](https://user-images.githubusercontent.com/43971542/114401167-f60d3500-9ba2-11eb-844e-51dcbf2ff417.jpg)

![171415745_857118218478677_3474343779610990924_n](https://user-images.githubusercontent.com/43971542/114403868-73d24000-9ba5-11eb-9b66-05effee7abac.jpg)

**Comment by sgong-pdftron** [comment]
@3imed-jaberi Could you provide a sample project where we can reproduce this? As you can see, the default sticky note is not giant, I'm unsure what could have caused this. Thanks.

**Comment by 3imed-jaberi** [comment]
@sgong-pdftron, you can use this [sample project](https://github.com/PDFTron/react-native-sample) .. just you need to change the code inside `DocumentViewer.tsx` file with this ;

```tsx
import React, { useEffect, useRef, useState } from "react";
import { Platform } from "react-native";
import { DocumentView, Config } from "react-native-pdftron";
import { DocumentViewerProps } from "../App";

const DocumentViewer = ({ route, navigation }: DocumentViewerProps) => {
  const { document } = route.params;

  const [annotationData, setAnnotationData] = useState('')

  const viewerRef = useRef(null)

  useEffect(() => {
    if (annotationData) {
      // console.log(annotationData);
      
      const { id, pageNumber, rect: { x1, x2, y1, y2 } } = annotationData

      viewerRef
        .current
        .setPropertiesForAnnotation(id, pageNumber, {
          rect: { x1, x2, y1, y2 },
          contents: JSON.stringify({ ok: true, msg: 'Hello World !'})
        })
        .then(console.log('>>>>>>> success loaded!'))
        .catch(console.log('>>>>>>> failed loaded!'))
    }
  }, [annotationData])

  return (
    <DocumentView
      ref={viewerRef}
      document={document}
      showLeadingNavButton={true}
      leadingNavButtonIcon={
        Platform.OS === "ios"
          ? "ic_close_black_24px.png"
          : "ic_arrow_back_white_24dp"
      }
      onLeadingNavButtonPressed={() => navigation.goBack()}
      overrideBehavior={[Config.Actions.stickyNoteShowPopUp]}
      onBehaviorActivated={async ({ action, data }) => {
        try {
          if (action === Config.Actions.stickyNoteShowPopUp) {
            const xfdfCommand = await viewerRef.current.exportAnnotations()
            if (xfdfCommand.includes('LocationPin')) {
              setAnnotationData(data)
            }
          }
        } catch (error) {
          console.log('something worng.');
        }
      }}
    />
  );
};

export default DocumentViewer;
```

**Comment by sgong-pdftron** [comment]
@3imed-jaberi I did what you mentioned, however I'm not seeing what you are reporting. When I used your code snippet, on my end, it seems like no behaviour change compare to original sample. Could you please send a complete sample?

**Comment by 3imed-jaberi** [comment]
@sgong-pdftron, this is a complete sample: https://github.com/3imed-jaberi/react-native-sample/tree/complete-sample-issue-228


![xxx-flow](https://user-images.githubusercontent.com/43971542/114954344-a062b200-9e5a-11eb-9d4e-f3ed06e99ad3.gif)

**Comment by sgong-pdftron** [comment]
@3imed-jaberi thanks for the project, I understand the problem now. When calling `onBehaviorActivated`, the viewer returns you the sticky note location in screen space (relative to your screen), whereas when you set annotation property, it expects page space. See an article explaining the differences here: https://www.pdftron.com/documentation/android/guides/basics/coordinates.

So the question I have for you here is what are you trying to achieve with the location?, are you trying to change the location?

Thanks.

**Comment by 3imed-jaberi** [comment]
@sgong-pdftron, I wanted to save my form data inside the sticky note, and the behavior that I adopted (use `importAnnotationCommand `) was working until it resulted in an error (`[Error: XML Parsing error]`) then @Maxwell-Yang-PDFTron suggested that I use another method, which is through `setPropertiesForAnnotation` and use the data object provided by  `onBehaviorActivated` but here I faced this problem.

**Comment by 3imed-jaberi** [comment]
@sgong-pdftron, @Maxwell-Yang-PDFTron, sorry for the late reply.. Thank you, I appreciate your support 🙏 it works well.
