### ISSUE TITLE
doesn't support Persian search

### ISSUE THREAD

**Issue by mahdidarzi** [PDFTron/pdftron-react-native#23]
when i search Persian it doesn't work

when ever i search a total word it cant be found like : 'سلام' 
but when ever i search a single character its work fine. like : 'س'

**Comment by sgong-pdftron** [comment]
@mahdidarzi could you post a video demo? For Persian language to work, you will need to have right to left turned on, could you check if you have that enabled?

**Comment by sgong-pdftron** [comment]
No more info obtain, close for now
