### ISSUE TITLE
Disable stamp and multi select inside Insert annotation

### ISSUE THREAD

**Issue by sertiano93** [PDFTron/pdftron-react-native#234]
I want my users to only be able to sign and read documents but I can't seem to find a way to hide the stamp and Multi Select inside the insert annotation. Do you know which one of the tools it is that corresponds to stamp and multi-select because I have tried them all without any success to hide it .

My second question is regarding inserting an option to "send" the document, i.e when the user have edited it , he or she should be able to either save it or send it through the chat that the user is working inside.

`
<DocumentView

        document={path}

        showLeadingNavButton={true}

        leadingNavButtonIcon={Platform.OS === 'ios' ? 'ic_close_black_24px.png' : 'ic_arrow_back_white_24dp'}

        onLeadingNavButtonPressed={this.onLeadingNavButtonPressed}

        hideTopToolbars={false}

        hideTopAppNavBar={false}

        hideDefaultAnnotationToolbars={[ 

          Config.DefaultToolbars.View,

          Config.DefaultToolbars.Annotate,

          Config.DefaultToolbars.Draw,

          Config.DefaultToolbars.Measure,

          Config.DefaultToolbars.Pens,

          Config.DefaultToolbars.Favorite,
         ]}

        disabledTools={[

          Config.Tools.annotationCreateStamp, 

          Config.Tools.annotationCreateFileAttachment,

          Config.Tools.annotationCreateRubberStamp,

          Config.Tools.annotationCreateStamp,

        ]}
      />
`

![Simulator Screen Shot - iPhone 11 Pro - 2021-03-19 at 15 33 54](https://user-images.githubusercontent.com/24451953/111796531-8f109f00-88c8-11eb-98db-ee1602831cec.png)

**Comment by Maxwell-Yang-PDFTron** [comment]
Hello @sertiano93. Regarding your first question, there are some internal TODOs for toggling some of the tools, which would be updated (maybe not in the near future). In the meantime, based on your requirement, you could use something like this using [annotationToolbars](https://github.com/PDFTron/pdftron-react-native/blob/master/API.md#annotationtoolbars) to work around it:

`
const myToolbar = {
      [Config.CustomToolbarKey.Id]: 'CustomInsert',
      [Config.CustomToolbarKey.Name]: 'Insert', 
      [Config.CustomToolbarKey.Icon]: Config.ToolbarIcons.Insert,
      [Config.CustomToolbarKey.Items]: [Config.Tools.annotationCreateSignature, Config.Buttons.undo, Config.Buttons.redo]
};
`

`
return (
  <DocumentView
      ref={(c) => this._viewer = c}
      annotationToolbars={[myToolbar]}
    />
);
`


Regarding your second question, by sending through chat, do you mean working in a collaboration environment? If you are just looking for a listener for when the document is updated, then [onAnnotationChanged](https://github.com/PDFTron/pdftron-react-native/blob/master/API.md#onannotationchanged) could be good choice. As for saving or sending the document, we have [saveDocument](https://github.com/PDFTron/pdftron-react-native/blob/master/API.md#savedocument). This saves the document and returns the path to the document in your file system.

If this does not solve your issue, feel free to comment below.

**Comment by sertiano93** [comment]
@Maxwell-Yang-PDFTron  
Thanks for the answers. It was what I needed !
