### ISSUE TITLE
Can't see annotations created by the currentUser with collabEnabled

### ISSUE THREAD

**Issue by HelloTiago** [PDFTron/pdftron-react-native#248]
**Describe the bug**
Annotations created by the current user don't show up when importing annotations via `importAnnotationCommand` with `collabEnabled` and `currentUser` set to the current user's name. Only annotations created by other users with a different name will show up.

**Steps to Reproduce the Problem**
1. Initialize `DocumentView` with `collabEnabled` and the currentUser's name:
```
<DocumentView
      ref={forwardedRef}
      document={document}
      padStatusBar
      hideToolbarsOnTap={false}
      collabEnabled
      currentUser="John Doe"
      onPageChanged={({ pageNumber }) => {
        setDocCurrentPage(pageNumber);
        loadAnnotationsForPage(pageNumber);
      }}
      onExportAnnotationCommand={handleAnnotationChange}
    />
```
2. Highlight some text in the document with currentUser set to "John Doe".
3. Set `currentUser="Jane Doe"` and highlight more text.
4. Export the annotations to XFDF and them import them on a clean instance of the document.
```
pageAnnotations.forEach((annotation) => {
        forwardedRef.current.importAnnotationCommand(annotation.xfdf, true);
});
```
5. Jane Doe will be able to see John Doe's annotations but not her own annotations.

**Expected behavior**
I should be able to see the annotations that I previously created, not just other people's.

**Platform/Device Information (please complete the following information if applicable):**
 - Platform: iOS
 - Device: iPad Air 4th generation
 - OS: iOS 14.4

**Comment by Maxwell-Yang-PDFTron** [comment]
Hi @HelloTiago, unfortunately I cannot reproduce this bug following your steps. It is highly unlikely that this is an issue with our native SDK. Based on your implementation, it seems you are storing the xfdf commands whenever there is an annotation change in the document, and importing all of them onto a clean document. This should be a viable way to import the annotations. If you are sure that your implementation is correct, would you mind attaching a runnable example for us? Or just the xfdf Commands that you exported would be helpful too. Thanks.

**Comment by HelloTiago** [comment]
Hi @Maxwell-Yang-PDFTron , thanks for getting back to me.

I can provide the xfdf commands, absolutely. It's worth adding that I also have an instance of PDFTron running in a web app, which is storing & reading from the same database as the React Native instance, and the web version doesn't have this issue - all annotations are displayed correctly, wether I added them via the RN instance or via the web, or if they were added by me or a different user.

Here's the XML for an annotation created via the React web app:
```
<?xml version="1.0" encoding="UTF-8" ?><xfdf xmlns="http://ns.adobe.com/xfdf/" xml:space="preserve"><annots><highlight page="0" rect="237.02,596.212,374.972,637.7199999999999" color="#FFCD45" flags="print" name="2a0b7d9a-79db-e709-1290-6553c1042f43" title="Tiago Duarte" subject="Highlight" date="D:20210405140548+01'00'" creationdate="D:20210405140548+01'00'" coords="237.02,637.7199999999999,374.972,637.7199999999999,237.02,596.212,374.972,596.212"><contents>Contract</contents></highlight></annots></xfdf>
```

And here's the XML for an annotation added via the React Native app, for the exame same string in the same PDF, by the same user:
```
<?xml version="1.0" encoding="UTF-8" ?><xfdf xmlns="http://ns.adobe.com/xfdf/" xml:space="preserve"><annots><highlight style="solid" width="1" color="#FFFF00" opacity="1" creationdate="D:20210405132121Z" flags="print" date="D:20210405132121Z" name="22DE6A5C-7F90-4853-AB13-87E9DC125271" page="0" coords="237.02,637.72,374.972,637.72,237.02,596.212,374.972,596.212" rect="232.698,596.212,379.294,637.72" title="Tiago Duarte" xmlns="http://ns.adobe.com/xfdf/">
			<popup date="D:20210405132121Z" page="0" rect="232.698,596.212,379.294,637.72"/>
			<contents>Contract</contents>
			<apref blend-mode="multiply" y="637.72" x="232.698" gennum="1" objnum="765"/>
		</highlight></annots></xfdf>
```

Something I noticed right away is that the React Native has a lot of tab characters in it. I don't think this is the reason behind the issue but the output from the web version does seem "better" (cleaner?).

Both XMLs will render an annotation correctly in the web app, but in the React Native version neither will show up if they match the currentUser prop.
Thanks!

**Comment by Maxwell-Yang-PDFTron** [comment]
Hi @HelloTiago, I could successfully import the xfdf you have provided. And the space and tabs between xfdf string do not matter for correctness.

Just to be sure, which API calls from our wrapper are you using to export the annotations and import them to the clean document? The 2 xfdf strings you have provided are in the structure of xfdf for annotation, not xfdf command for import. An xfdf command would have add, delete and modify tags. Thanks.

**Comment by HelloTiago** [comment]
Hi @Maxwell-Yang-PDFTron - I can import the xfdf's as well, I just can't see them if the author of the annotations matches the current author. Could you see them if you set the `currentUser` to match the annotation author, `Tiago Duarte`?

Below is how we're exporting the annotations from PDFTron. Since we're storing them in a database and don't need to keep track of the full xfdf command with add/modify/delete instructions, we only store the actual XML of the annotation. The web version of pdftron provides this out of the box but for React Native we had to do some manual parsing to get there:

```
const handleAnnotationChange = ({ action, xfdfCommand }) => {
    if (action === 'add') {
      const doc = new DOMParser().parseFromString(xfdfCommand, 'text/xml');
      const data = doc.documentElement.getElementsByTagName('add')[0];
      const node = data.childNodes[1];
      const annotationXfdf = node.toString();

      console.log('annotationXfdf: ', annotationXfdf);
      console.log('full annotation xml string for DB: ', `<?xml version="1.0" encoding="UTF-8" ?><xfdf xmlns="http://ns.adobe.com/xfdf/" xml:space="preserve"><annots>${annotationXfdf}</annots></xfdf>`);
    }
    // handle other actions (modify/delete)
};
```

**Comment by Maxwell-Yang-PDFTron** [comment]
@HelloTiago, I still cannot replicate this issue, unfortunately. Could you take a look at [this branch](https://github.com/PDFTron/pdftron-react-native/tree/collab-current-user-annotation) and run the example app in it? I have modified the App.js to showcase this issue, which does not occur in this case. If there is anything missing from this example, feel free to comment below. Thank you!

**Comment by HelloTiago** [comment]
@Maxwell-Yang-PDFTron I tested the example app and it works. It seems like you're using a different method to import annotations though, `importAnnotations`, while I'm using `importAnnotationCommand`. I tried using the same in my loop of the pages' annotations (the documents I'm working with tend to get a lot of annotations so I'm only importing them page by page when the user changes pages), like so:

```
pageAnnotations.forEach((annotation) => {
        forwardedRef.current.importAnnotations(annotation.xfdf);
});
```

But only the last annotation in the array gets added, which makes me think that this method clears previously imported annotations to the document instead of appending - is that correct?

The method I'm using, `importAnnotationCommand`, does print out all the annotations - just not the ones that were made by the current user. I've also noticed some instances where a few link annotations just don't render, but that's another issue which I need to gather more details on first.

Is there an alternative way to do this that you recommend? Thank you!

**Comment by Maxwell-Yang-PDFTron** [comment]
Hi @HelloTiago, it is definitely doable to import annotation commands based on page changes, but it is better have some checks to avoid importing the same command every time the viewer scrolls to the same page. You could import the same command multiple times, but every time the command is imported, the screen will re-render, which is not recommended.

I have updated the [branch]((https://github.com/PDFTron/pdftron-react-native/tree/collab-current-user-annotation) to use importAnnotationCommand and onPageChanged event. This is importing 2 commands (one for current user, one for other user) every time a page changes (although this does indeed import the same command every time you hits the page which is not the best, but it is just for demonstration) for the first 3 pages of the sample pdf. Hope you could look again and comment below. Thanks.

**Comment by HelloTiago** [comment]
Hi @Maxwell-Yang-PDFTron , thanks for the recommendations. I've got it set up so it only imports annotations once per page.

I forked your example and updated it with the PDF that I'm using as well as two annotations exported from that document and the issue is still present: https://github.com/HelloTiago/pdftron-react-native/tree/collab-current-user-annotation
The annotation on page 1 is for the current user and the annotation on page 2 is for another user. The second one loads fine, but the first one doesn't.

Like I mentioned before this issue _doesn't_ occur on the Web version of PDFTron - only in the React Native port, so there must be something going on with the XML import in the react native version :/ Thanks again!

**Comment by Maxwell-Yang-PDFTron** [comment]
Hi @HelloTiago, I have made changes again to the [branch](https://github.com/PDFTron/pdftron-react-native/tree/collab-current-user-annotation) which uses your example. I finally spotted the problem after seeing my mistake:

This is an xfdf for importAnnotations:
``
`<?xml version="1.0" encoding="UTF-8" ?><xfdf xmlns="http://ns.adobe.com/xfdf/" xml:space="preserve"><annots><highlight page="1" rect="237.02,596.212,374.972,637.7199999999999" color="#FFCD45" flags="print" name="9c180db5-899b-2b3f-4cbf-8cef7e98b2e9" title="Tiago Duarte" subject="Highlight" date="D:20210413171202+01'00'" creationdate="D:20210413171202+01'00'" coords="237.02,637.7199999999999,374.972,637.7199999999999,237.02,596.212,374.972,596.212"><contents>Contract</contents></highlight></annots></xfdf>`
``

This is an xfdfCommand for importAnnotationCommand:
``
`<?xml version="1.0" encoding="UTF-8" ?><xfdf xmlns="http://ns.adobe.com/xfdf/" xml:space="preserve"><add><highlight page="0" rect="237.02,596.212,374.972,637.7199999999999" color="#FFCD45" flags="print" name="9c180db5-899b-2b3f-4cbf-8cef7e98b2e9" title="Tiago Duarte" subject="Highlight" date="D:20210413171202+01'00'" creationdate="D:20210413171202+01'00'" coords="237.02,637.7199999999999,374.972,637.7199999999999,237.02,596.212,374.972,596.212"><contents>Contract</contents></highlight></add><modify /><delete /><pdf-info import-version="3" version="2" xmlns="http://www.pdftron.com/pdfinfo" /></xfdf>`
``

So I was using the wrong call in the previous commit of the branch (sorry about that!). It is just a coincidence that importAnnotationCommand works for non-current user xfdf, which you should not use.

The correct way is to importAnnotationCommand with the the xfdf command, that is indicated with the <add></add><modify /><delete /> case. The new commit works, feel free to comment again if there are more questions. Thanks!
