### ISSUE TITLE
Build Failed [ANDROID] (not Expo version)

### ISSUE THREAD

**Issue by NishadPatilMuzero** [PDFTron/pdftron-react-native#257]
Error Description:-
    * What went wrong:
             Could not determine the dependencies of task ':app:mergeDebugAssets'.
                 > Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
                      > Could not find com.pdftron:pdftron:8.1.3-beta12.

 *All the installation steps are followed properly as per the link:
                      https://github.com/PDFTron/pdftron-react-native#installation

![issue](https://user-images.githubusercontent.com/80349070/114882744-e4859080-9e21-11eb-9c48-3852ecb0c858.PNG)
![issue1](https://user-images.githubusercontent.com/80349070/114882922-1139a800-9e22-11eb-814b-1213c04962bd.PNG)

Platform/Device Information
 - Platform: Android
 - Device:  Redmi note 5 pro
 - OS: Android Pie

**Comment by sgong-pdftron** [comment]
@NishadPatilMuzero In your search path, I don't see the required path for PDFTron "https://pdftron-maven.s3.amazonaws.com/snapshot". This should be part of your root project setting unless somehow it was overwritten by your application. Could you please double check that

    maven {     url "https://pdftron-maven.s3.amazonaws.com/snapshot" }

is inside node_modules/react-native-pdftron/android/build.gradle

As well as check there is nothing in your main build.gradle that could have overwritten it?

Thanks.

**Comment by NishadPatilMuzero** [comment]
Hey @sgong-pdftron,
I checked the **build.gradle** file 

             `maven {     url"https://pdftronmaven.s3.amazonaws.com/snapshot"}`

is present in _node_modules/react-native-pdftron/android/build.gradle_ file.

In _android/build.gradle_ I haven't changed anything.

In _android/app/build.gradle_ I have just added 

`  dexOptions {
        javaMaxHeapSize "4g"
    }`
.........
 `signingConfigs {
        release {
.......
 }
    }`



Thank You.

**Comment by sgong-pdftron** [comment]
@NishadPatilMuzero Are you able to reproduce here: https://github.com/PDFTron/react-native-sample. Or could you share a sample project?

**Comment by NishadPatilMuzero** [comment]
@sgong-pdftron I have created a new sample project but an error occurring while building

* What went wrong:
Execution failed for task ':app:packageDebug'.
> A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
   > java.lang.OutOfMemoryError (no error message)
  
Here is the link of the project, please check-

[](https://github.com/Dontag/PDFTron.git)

**Comment by sgong-pdftron** [comment]
@NishadPatilMuzero I downloaded your project, and all I did is "npm install" on root, then import the project to Android Studio then build, it works as expected:

![Screen Shot 2021-04-19 at 4 37 02 PM](https://user-images.githubusercontent.com/20527369/115316128-99bf8d80-a12d-11eb-9f45-04f0c545e28d.png)

I suspect your environment is not setup properly with Android. Could you try maybe install the latest version of Android Studio to ensure the environment is setup properly?

Thanks.

**Comment by NishadPatilMuzero** [comment]
@sgong-pdftron  ill check from my side.

**Comment by NishadPatilMuzero** [comment]
Hey @sgong-pdftron,
The problem was related to gradle this problem is solved.
thank you.

**Comment by brerdem** [comment]
Same here @sgong-pdftron. I did check installation steps and nothing's wrong, only thing I'm using Gradle v6.4 with Android Gradle plugin v4.0.2. 

![image](https://user-images.githubusercontent.com/778976/147927895-a0c3ac46-ce0d-471d-8607-73a08815b51e.png)

**Comment by sgong-pdftron** [comment]
@brerdem based on https://github.com/PDFTron/pdftron-react-native/issues/447, it looks like you were able to use it no problem?

**Comment by brerdem** [comment]
@sgong-pdftron I was able to run it after copying lines from `node_modules/react-native-pdftron/android/build.gradle` to `android/app/build.gradle` and `android/build.gradle` respectively. Still this needs to be investigated since the solution I come up with is not very reliable I think.
