### ISSUE TITLE
Can't build app after iOS Pdftron version updated

### ISSUE THREAD

**Issue by shrooosher** [PDFTron/pdftron-react-native#264]
**Describe the bug**
When I'm trying to build latest pdftron-react-native latest master version with PDFNet (9.0.0.77669) Pod - build fails with error
RNTPTDocumentView.m:1618:28: 'pageFitsBetweenBars' is unavailable: This API is no longer availble.

**Steps to Reproduce the Problem**
1. Create new react app or replace "react-native-pdftron": "file:../" in example app for "react-native-pdftron": "github:PDFTron/pdftron-react-native"
2. install all dependencies
3. Try to build app

**Platform/Device Information (please complete the following information if applicable):**
 - Platform: iOS

**Additional context**
We use appcenter to build apps and every time when you have an update of your app, since you don't have any versions for react native and iOS always download latest version of your app - we have to update Podfile.lock to build app. Is there any way to avoid that and not update dependency every time when you updating your app?

**Comment by JamieDass** [comment]
Thank you for letting us know, I will close this issue now.
