### ISSUE TITLE
Feature Request: Implement Completion Handler for Document Saves

### ISSUE THREAD

**Issue by DanielCender** [PDFTron/pdftron-react-native#28]
### Request
-------------

__Problem:__ In the current wrapper, there is no clearly-available method for detecting a successful save to a local location. 

Common enterprise use cases for React Native applications require the use of cloud storage as a save location or background synchronization with cloud storage. 

There are some useful event handlers on the native iOS PTDocumentViewController class which could hold value for React Native users if implemented into the wrapper.

__Example workflow in mind:__
- Users scan documents into the application. Once they are saved (using another 3rd party SDK), those files are uploaded to an AWS S3 storage bucket.
- Now, the application lists all documents for a user's role in a screen.
- When selected, the document is opened with tooling from PDFTron's RN wrapper.
- Once the document is marked up/signed/annotated and saved, the hope is to re-upload that updated document to S3 storage upon a successful local save.

On the PTDocumentViewController class, the `-saveDocument:completionHandler:` handler [here](https://www.pdftron.com/api/ios/Classes/PTDocumentViewController.html#/c:objc(cs)PTDocumentViewController(im)saveDocument:completionHandler:) would seem to be a good fit for allowing React Native developers to implement more advanced functionality that requires receiving a callback status from PDFTron.

**Comment by Frekansapp** [comment]
I need this feature too

**Comment by Maxwell-Yang-PDFTron** [comment]
Hi @DanielCender and @Frekansapp, this feature could now be achieved with `saveDocument`(https://github.com/PDFTron/pdftron-react-native/blob/master/API.md#savedocument). The returned promise will resolve/reject if document is saved successfully/unsuccessfully.
