### ISSUE TITLE
Annotation methods

### ISSUE THREAD

**Issue by brerdem** [PDFTron/pdftron-react-native#286]
How can I access annotation specific methods like `getReplies()` as we have in Web SDK?

**Comment by sgong-pdftron** [comment]
@brerdem this is not supported at the moment. May I ask if you are using collaboration mode in the React Native SDK? Could you submit a feature request through our ticketing system https://www.pdftron.com/support/? Thanks.

**Comment by brerdem** [comment]
@sgong-pdftron Thanks. I'm not using collaboration mode rather heavily modify annotations. Is there a way you can suggest without messing with XML too much?

**Comment by sgong-pdftron** [comment]
@brerdem I don't recommend any messing with the XML (if you are referring to XFDF), that is too error prone. the best way is to use the collaboration mode and we look into expose getReplies for you. Is there a PDF document with the replies, or sample XFDF you could provide so we understand your use case better?

**Comment by brerdem** [comment]
@sgong-pdftron Yes I'm referring to XFDF string. There are many methods I'm using, `getReplies` is just one of them. There is no specific use case, all I want is record the text replies along with their user and date. Below I'm giving the list of functions currently I need. I'm currently migrating a Web app to mobile so I need them work as in Web SDK. Thanks

- getReplies()
- createAnnotationReply()
- setCustomData()
- getCustomData()
- get / set  StrokeColor
- redrawAnnotation (I don't know if it's necessary for mobile)
- get / set Author
- DateAdded
- deleteAnnotation

**Comment by sgong-pdftron** [comment]
@brerdem would it be possible if you could submit an official feature request here: https://www.pdftron.com/support so it's easier for us to track? thanks.

**Comment by brerdem** [comment]
Sure will do. Thanks
