### ISSUE TITLE
Entering a text on the iOS does not get saved every time

### ISSUE THREAD

**Issue by shrooosher** [PDFTron/pdftron-react-native#287]
**Describe the bug**
When adding text annotation and hiding keyboard. Text don't save every time.

**Steps to Reproduce the Problem**
1. Select text annotation
2. Enter text
3. Hide keyboard (press done) or press on document
4. Text don't save every time.

**Expected behavior**
Text saved every time.

**Platform/Device Information (please complete the following information if applicable):**
 - Platform: iOS
 - Device: iPhone 11 Pro Max
 - OS: iOS 14.5

**Additional context**
Sometimes works fine. Some times not. Need to try few time to reproduce.

**Comment by JamieDass** [comment]
Hi @shrooosher,

Thank you for reporting this. We are investigating.

Just to clarify in step 3:
> Hide keyboard (press done) or press on document
Does the issue occur for both of these methods of hiding the keyboard?

**Comment by shrooosher** [comment]
On "Hide keyboard (press done)"  can’t reproduce when press on document

**Comment by JamesTron** [comment]
Hi @shrooosher,

We are unable to reproduce the behaviour you've described. Could you please make sure you are using the latest version of the native PDFTron SDK (by running `pod update` in the folder with the file "Podfile" in it), and and also update to the latest code available on our ReatNative github repository, try again, and let us know what you see?

Thank you.

**Comment by shrooosher** [comment]
Hello. Can’t reproduce on new version. Thanks.

**Comment by shrooosher** [comment]
Can reproduce on latest version of PdfTron
https://user-images.githubusercontent.com/72397257/121882846-b9cc9100-cd19-11eb-9278-f479d886d1f7.mov

**Comment by shrooosher** [comment]
@JamesTron check video pls.
