### ISSUE TITLE
[Android] Annotation sticky note do not show pop up when using props `collabEnabled`

### ISSUE THREAD

**Issue by hatn98** [PDFTron/pdftron-react-native#288]
**Describe the bug**
I open the document with the latest version react-native-pdftron. After I adding prop **collabEnabled={true}**, the annotation tool `sticky note` does not show a pop-up.

**Steps to Reproduce the Problem**

1. Create new react app or replace "react-native-pdftron": "file:../" in example app for "react-native-pdftron": github:PDFTron/pdftron-react-native.
2. Install all dependencies.
3. Adding props **collabEnabled={true}**
4. Using annotation sticky note and see the issue.

**Screenshots**

This is the video link that I reproduce this issue:
https://youtu.be/HM6r4yqyIQo

**Platform/Device Information (please complete the following information if applicable):**
 - Platform: `Android`

**Comment by sgong-pdftron** [comment]
@hatn98 This is the expected behaviour. In Collaboration mode, you will need to click on the notes icon to display the annotation reply UI. Because in collaboration mode, notes are shown as "chats" as oppose to a single message. Could you please give it a try?

**Comment by hatn98** [comment]
@sgong-pdftron 
Thanks for your reply,
I will try again.
