### ISSUE TITLE
Is it possible to merge onAnnotationsChanged and onExportAnnotations events into one?

### ISSUE THREAD

**Issue by brerdem** [PDFTron/pdftron-react-native#293]
In my project I need to save changed annotations into my database along their ID and XFDF strings. Since there is no single method that gives me changed annotations with ID and XFDFI need to call both of these events. Is there a better way to do it?

Thanks

**Comment by sgong-pdftron** [comment]
@brerdem Thanks for bringing this up, we will look into add IDs as part of `onExportAnnotationCommand` API

**Comment by akwanpdf** [comment]
@brerdem IDs have now been added to `onExportAnnotationCommand` API, see #301. Thank you!
