### ISSUE TITLE
Entering a text on the iOS does not get saved every time 

### ISSUE THREAD

**Issue by shrooosher** [PDFTron/pdftron-react-native#295]
**Describe the bug**
When adding text annotation and hiding keyboard. Text don't save every time.

**Steps to Reproduce the Problem**
1. Select text annotation
2. Enter text
3. Hide keyboard (press done) or press on document
4. Text don't save every time.

**Expected behavior**
Text saved every time.

**Platform/Device Information (please complete the following information if applicable):**
 - Platform: iOS
 - Device: iPhone 11 Pro Max
 - OS: iOS 14.5

**Additional context**
Sometimes works fine. Some times not. Need to try few time to reproduce.
Can reproduce on latest version of PdfTron
https://user-images.githubusercontent.com/72397257/121882846-b9cc9100-cd19-11eb-9278-f479d886d1f7.mov

**Comment by damianimashaun** [comment]
This issue is still reproducible in "@pdftron/react-native-pdf": "3.0.2-beta.66",

**Comment by sgong-pdftron** [comment]
We are closing down issues section in favor of official Apryse support channel, please report issues through our official channel at https://apryse.com/support
