### ISSUE TITLE
Edit Menu Button still appears when disabled on Android

### ISSUE THREAD

**Issue by dcupidon** [PDFTron/pdftron-react-native#300]
**Describe the bug**
On Android, the edit menu button still appears in the toolbar although it has been included in `disabledElements`.

**Steps to Reproduce the Problem**
1. Include `disabledElements={[Config.Buttons.editMenuButton]}` within the props for `DocumentView`.
2. Run Android emulator.

**Expected behavior**
The edit menu button would not be visible in the toolbar, for example: 

<img width="378" alt="Screen Shot 2021-06-24 at 7 56 05 AM" src="https://user-images.githubusercontent.com/83605527/123299382-4facac80-d4ce-11eb-8ba1-b772da66e690.png">

The above screenshot is taken from an iPhone 12 mini running iOS 14.5.

**Screenshots**
<img width="372" alt="Screen Shot 2021-06-24 at 7 51 41 AM" src="https://user-images.githubusercontent.com/83605527/123298951-e3ca4400-d4cd-11eb-8e5a-b7295eb4930b.png">

**Platform/Device Information:**
 - Platform:Android
 - Device: Pixel 3a
 - OS: Android 11

**Additional context**
Full configuration of `DocumentView` used:

```javascript
<DocumentView
        ref={(c) => this._viewer = c}
        // hideDefaultAnnotationToolbars={[Config.DefaultToolbars.Annotate]}
        // annotationToolbars={[toolbar]}
        hideAnnotationToolbarSwitcher={false}
        hideTopToolbars={false}
        hideTopAppNavBar={false}
        document={this.state.docPath}
        padStatusBar={true}
        showLeadingNavButton={true}
        leadingNavButtonIcon={Platform.OS === 'ios' ? 'ic_close_black_24px.png' : 'ic_arrow_back_white_24dp'}
        onLeadingNavButtonPressed={this.onLeadingNavButtonPressed}
        // onDocumentLoaded={this.onDocumentLoaded}
        // onAnnotationChanged={this.onAnnotationChanged}
        onExportAnnotationCommand={this.onExportAnnotationCommand}
        // onAnnotationsSelected={this.onAnnotationSelected}
        onZoomChanged={this.onZoomChanged}
        readOnly={false}
        disabledElements={[Config.Buttons.userBookmarkListButton, Config.Buttons.editMenuButton]}
        disabledTools={[Config.Tools.annotationCreateLine, Config.Tools.annotationCreateRectangle]}
        fitMode={Config.FitMode.FitPage}
        layoutMode={Config.LayoutMode.Continuous}
        // annotationsListEditingEnabled={true}
        // showNavigationListAsSidePanelOnLargeDevices={true}
        // restrictDownloadUsage={false}
        // userBookmarksListEditingEnabled={true}
        photoPickerEnabled={true}
        autoResizeFreeTextEnabled={false}
        // collabEnabled={true}
        // currentUser={'Pdftron'}
      />
```

**Comment by sgong-pdftron** [comment]
We are closing down issues section in favor of official Apryse support channel, please report issues through our official channel at https://apryse.com/support
