### ISSUE TITLE
Unable to completely disable editing on certain annotation types

### ISSUE THREAD

**Issue by dcupidon** [PDFTron/pdftron-react-native#323]
**Describe the bug**
I exposed an API that disables editing on certain annotation types. While testing on Android, I noticed the following: when no tool is selected only annotation types that were not passed to the prop can be edited, but when a tool is selected any annotation can be edited.

**Steps to Reproduce the Problem**
1. Go to `DocumentView.js` and add `disableEditingByAnnotationType: PropTypes.array,` to `propTypes`.
2. Go to `src/main/java/com/pdftron/reactnative/viewmanagers/DocumentViewViewManager.java` and add the following:
```java
    @ReactProp(name = "disableEditingByAnnotationType")
    public void setDisableEditingByAnnotationType(DocumentView documentView, ReadableArray annotationTypes) {
        documentView.setDisableEditingByAnnotationType(annotationTypes);
    }
```
3. Go to `src/main/java/com/pdftron/reactnative/views/DocumentView.java` and add the following:
```java
    public void setDisableEditingByAnnotationType(ReadableArray annotationTypes) {
        int[] annotTypes = new int[annotationTypes.size()];
        for (int i = 0; i < annotationTypes.size(); i++) {
            String item = annotationTypes.getString(i);
            annotTypes[i] = convStringToAnnotType(item);
        }

        if (annotTypes.length > 0) {
            mToolManagerBuilder = mToolManagerBuilder.disableAnnotEditing(annotTypes);
        }
    }
```
4. Add the following to `App.js`:
```js
<DocumentView
   document={this.state.docPath}
   disableEditingByAnnotationType={Array of Config.Tools constants}
/>
```

**Expected behavior**
Taken from an iOS device:
https://user-images.githubusercontent.com/83605527/125500865-06dab43f-7537-4b3a-903b-7426a9d2098e.mp4

Here `[Config.Tools.annotationCreateTextHighlight, Config.Tools.annotationCreateTextSquiggly, Config.Tools.annotationCreateTextStrikeout]` were passed to the prop.

**Screenshots**
Taken from an Android device:
https://user-images.githubusercontent.com/83605527/125501427-3ef386c5-3191-4ecd-93a0-f0e68fa6b981.mp4

Here `[Config.Tools.annotationCreateEllipse, Config.Tools.annotationCreateTextSquiggly]` were passed to the prop.

**Platform/Device Information**
 - Platform: Android
 - Device: Pixel 3a
 - OS: Android 11 (API 30)

**Comment by sgong-pdftron** [comment]
We are closing down issues section in favor of official Apryse support channel, please report issues through our official channel at https://apryse.com/support
