### ISSUE TITLE
Current open tab or onTabChange event

### ISSUE THREAD

**Issue by HelloTiago** [PDFTron/pdftron-react-native#337]
There's support for Multi tabs but there's no way to know when the user changes tabs, or which tab is currently open.

A "onTabChange" event that returned the title of the current tab, for example, would be really helpful. Thanks.

**Comment by sgong-pdftron** [comment]
Hi, sorry for the late reply. Yes we can add tab changed event for sure

**Comment by sgong-pdftron** [comment]
This is now available:
https://github.com/PDFTron/pdftron-react-native/pull/370
Thanks.
