### ISSUE TITLE
iOS Export Error

### ISSUE THREAD

**Issue by rraczae** [PDFTron/pdftron-react-native#367]
**Describe the bug**
Our ios production build started failing when we included PDFTron with the  following error:

```
error: exportArchive: ipatool failed with an exception: #<CmdSpec::NonZeroExitException: $ /Applications/Xcode_12.4.app/Contents/Developer/usr/bin/python3 /Applications/Xcode_12.4.app/Contents/Developer/usr/bin/bitcode-build-tool -v -t /Applications/Xcode_12.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin --sdk /Applications/Xcode_12.4.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.4.sdk -o /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/ipatool20210817-13040-g368s/thinned-out/arm64/Payload/freetools.app/Frameworks/PDFNet.framework/PDFNet --generate-dsym /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/ipatool20210817-13040-g368s/thinned-out/arm64/Payload/freetools.app/Frameworks/PDFNet.framework/PDFNet.dSYM --strip-swift-symbols /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/ipatool20210817-13040-g368s/thinned-in/arm64/Payload/freetools.app/Frameworks/PDFNet.framework/PDFNet
Status: pid 14035 exit 1
```

Everything worked fine before, we pushed dozens of new builds.

**Steps to Reproduce the Problem**
Setup a build on AppCenter and try to run it.

**Expected behavior**

The app is built.

**Additional context**
There was another issue about this: https://github.com/PDFTron/pdftron-react-native/issues/155
In our case we set the build to XCode 12.4 so it has to be something else.

**Comment by JamesTron** [comment]
Like any iOS SDK, PDFTron requires an app that uses it to use the same version (or a later version) of Xcode that was used to compile the SDK. It looks like AppCenter has not updated to Xcode 12.5 yet, which is unfortunately causing problems for many AppCenter customers. https://github.com/microsoft/appcenter/issues/2185#issuecomment-875123079

We suspect this is behind the problem, however you can work around this particular problem by turning bitcode off. That said, any production build really should be built using Xcode 12.5 or later. Hopefully AppCenter updates soon.
