### ISSUE TITLE
[Question] Drag/drop signature to cross page

### ISSUE THREAD

**Issue by hatn98** [PDFTron/pdftron-react-native#369]
Hi,
Is possible to drag/drop a signature to cross page?

**Comment by sgong-pdftron** [comment]
Hi, this is not possible at the moment. Just to clarify, do you mean move a signature from one page to the next page?

**Comment by hatn98** [comment]
Thanks for your reply,
Yes, I want to move a signature from one page to the next page.

**Comment by sgong-pdftron** [comment]
@hatn98 as this is a new feature request, may I ask what timeline are you looking at and whether this is blocking your release? Would you be able to submit a proper feature request here: https://www.pdftron.com/form/feature-request/. Thanks.
