### ISSUE TITLE
Disable some unknown tools

### ISSUE THREAD

**Issue by brerdem** [PDFTron/pdftron-react-native#391]
**Describe the bug**

I'd like to disable marked buttons on screenshot. Currently they are listed as **unknown tool** and 

**Expected behavior**
Those buttons should have tool names and should be hidden when included in `disabledButtons` array

**Screenshots**
![image](https://user-images.githubusercontent.com/778976/136785379-ada8102e-81ec-4779-8343-1a054fcfdf55.png)

**Platform/Device Information (please complete the following information if applicable):**
 - iOS 14.4

**Comment by brerdem** [comment]
Hi,

Updated to latest version (3.0.2 - beta 19) I'm still seeing Smart Pen tool even it's in the disabled tools list. 

![image](https://user-images.githubusercontent.com/778976/143232554-832aa7c0-70b1-4af7-ae2c-a4839afcfb53.png)

**Comment by dcupidon** [comment]
Thanks for bringing this to our attention. We will let you know when an update that fixes the issue has been released.

**Comment by brerdem** [comment]
any update on this?

**Comment by dcupidon** [comment]
The fix for this should come after the next official release of the native iOS library

**Comment by dcupidon** [comment]
Support for disabling the Smart Pen tool has been added on version 3.0.2-beta.29
