### ISSUE TITLE
Facing issue while editing

### ISSUE THREAD

**Issue by sakthivelvthink** [PDFTron/pdftron-react-native#421]
**Describe the bug**
 After editing using sketch and can't save the edit document from the file path .

**Steps to Reproduce the Problem**

1. View one pdf document
2. Edit by sketch pencil
3. Save it in different file path
4. View the document from the newly saved path.

**Expected behavior**
Edited document should be viewable from newly saved path

**Screenshots**
https://user-images.githubusercontent.com/53554370/142632416-7304b765-9b34-4309-9bb4-4b583f43a2a9.jpeg

**Platform/Device Information (please complete the following information if applicable):**
 - Platform: Android
 - Device: Android redmi y2  version:9
 - OS: [e.g. iOS8.1, Android Nougat]

**Additional context**
 Headtic issues fix it as soon as possible

**Comment by sgong-pdftron** [comment]
@sakthivelvthink Could you please share the code snippet of usage of the viewer including how you are saving to a new path? Ideally a sample project that will allow us to reproduce this issue will get us a solution fastest.

Thanks.

**Comment by sakthivelvthink** [comment]
Hi sgong,
 If i am free version . Edit option will hide automatically after the first edit?

**Comment by sgong-pdftron** [comment]
Hi @sakthivelvthink , PDFTron is a commercial solution so there isn't a free version. There is a trial version that you can use during your trial period. You get to try all functionalities. Could you please elaborate on the exact problem and how to reproduce it? We may be able to help if we can reproduce it on our end. Thanks.

**Comment by hemavthink** [comment]
@sgong-pdftron In Android, Editing and save the document using the sketch pencil. After saving, open the document, sketch pencil edited are  cleared(not saving) and also editing tools are not visible.

**Comment by sgong-pdftron** [comment]
Please reopen or contact PDFTron support if there is any further issues.
