### ISSUE TITLE
Latest podspec broken for React Native

### ISSUE THREAD

**Issue by ghills** [PDFTron/pdftron-react-native#43]
**Describe the bug**
Updating pod with the latest PDFNet pod from https://www.pdftron.com/downloads/ios/cocoapods/pdfnet/latest.podspec breaks the build of the React Native iOS project.

Error is:

> node_modules/react-native-pdftron/ios/RNTPTDocumentView.h:9:9: 'Tools/Tools.h' file not found

This is in a project that was previously working with the PDFNet pod. I also created a new react native project and followed the steps on the README to integrate pdftron-react-native and got the same build error.

**Steps to Reproduce the Problem**
Update pods with a Podfile containing:

```
  pod 'PDFNet', podspec: 'https://www.pdftron.com/downloads/ios/cocoapods/pdfnet/latest.podspec'
  pod 'RNPdftron', :path => '../node_modules/react-native-pdftron'
```

**Screenshots**

**Platform/Device Information (please complete the following information if applicable):**
 - Platform: iOS
 - Device: iPhone 11 simulator
 - OS: iOS13.2

**Additional context**
I pulled the latest PDFNet podspec file and the previous versions podspec file (which I believe I was previously using) and noticed that where previously it had:

>   s.preserve_paths      = 'PDFNet.framework', 'Tools.framework'
>   s.vendored_frameworks = 'PDFNet.framework', 'Tools.framework'

it now has

>   s.preserve_paths      = 'PDFNet.framework'
>   s.vendored_frameworks = 'PDFNet.framework'

this leads me to believe that the 'no tools' variant of the PDFNet podspec file was erroneously uploaded to https://www.pdftron.com/downloads/ios/cocoapods/pdfnet/latest.podspec.

[latest.podspec.txt](https://github.com/PDFTron/pdftron-react-native/files/4227432/latest.podspec.txt)

[7.0.4.73314.podspec.txt](https://github.com/PDFTron/pdftron-react-native/files/4227442/7.0.4.73314.podspec.txt)

**Comment by dluco-pdftron** [comment]
Hi there,
Thank you for letting us know about this issue.
There was an issue with the PDFNet CocoaPod's latest.podspec that has now been fixed. Please try re-installing the PDFNet CocoaPod in the ios/ directory of your project and let us know if you still experience the problem. You may need to clear your pod cache with the following command:
`pod cache clean 'PDFNet' --all`

**Comment by CorvinSteindl** [comment]
Having currently the same issue.
`pod cache clean 'PDFNet' --all` did not worked for me.

**Comment by ghills** [comment]
Looks like it is working for me now - thanks
