### ISSUE TITLE
(iOS) `onDocumentLoaded` returns the wrong path

### ISSUE THREAD

**Issue by dcupidon** [PDFTron/pdftron-react-native#432]
**Describe the bug**
The iOS version of `onDocumentLoaded` returns the same value that was passed into the `document` prop.

**Steps to Reproduce the Problem**
1.  Pass the variable below into the `onDocumentLoaded` prop.
```js
  onDocumentLoaded = (path) => {
    console.log("File path is: " + path);
  }
```
2. Run the Android simulator and see that the outputted path refers to the local cached files.
3. Run the iOS simulator and see that the outputted path is the same as the value passed into the `document` prop.

**Expected behavior**
The iOS version of `onDocumentLoaded` should have the same output as its Android counterpart.

**Platform/Device Information**
 - Platform:iOS
 - Device: iPad Pro 12.9 inch 5th generation
 - OS: iOS 15.0

**Additional context**
This issue looks to be directly in the React Native wrapper. The `documentLoaded` method in `RNTPTDocumentViewManager.m`, which returns the event listener's response, is sending the `document` prop. See screenshot below:

<img width="532" alt="Screen Shot 2021-12-03 at 11 13 11 AM" src="https://user-images.githubusercontent.com/83605527/144659720-ee40a0c1-03d0-45b4-9bcc-7ca0eff25c56.png">

**Comment by sgong-pdftron** [comment]
We are closing down issues section in favor of official Apryse support channel, please report issues through our official channel at https://apryse.com/support
