### ISSUE TITLE
Empty space of Annotation Toolbar Switcher

### ISSUE THREAD

**Issue by brerdem** [PDFTron/pdftron-react-native#433]
When I try to hide toolbar switcher by setting `hideAnnotationToolbarSwitcher` to `true`, the switch element disappears but also leaves an empty space as seen in screenshot. How can I completely remove it?

iOS 14.1
PdfTron v3.0.2

![image](https://user-images.githubusercontent.com/778976/145049149-3888a267-334b-4ec1-a262-7efd6378f5f6.png)

**Comment by akwanpdf** [comment]
In the [example App.js](https://github.com/PDFTron/pdftron-react-native/blob/master/example/App.js), I set `hideAnnotationToolbarSwitcher` to `true` but was unable to replicate the issue in iOS 14.1. I also tried iOS 15.0 just in case, and it also worked normally. 

Could you please paste your `App.js` so I can take a look at the rest of your configuration? Thanks.

<img width="468" alt="image" src="https://user-images.githubusercontent.com/83605632/145087971-b806f7b2-5097-43bb-9619-ae04bfb319f8.png">

**Comment by brerdem** [comment]
Hi @akwanpdf . My code as follows. I just made a custom header and I don't use any toolbar/appbar other than annotation toolbar. I'm also hiding all tools and buttons except the ones listed in the  arrays below. Thanks

`return (
    <View style={styles.container}>
      <View style={styles.topBar}>
        <Button
          icon={{name: 'close'}}
          onPress={() => navigation.goBack()}
          type={'clear'}
        />
        <Input
          inputContainerStyle={styles.searchField}
          containerStyle={[styles.searchField, {width: width - 160}]}
          inputStyle={{fontSize: 14, paddingLeft: 5, margin: 0}}
          value={searchTerm}
          onChangeText={handleChangeText}
          leftIcon={<Icon type={'ebookbox'} name={'menu-search'} size={22} />}
          leftIconContainerStyle={{paddingLeft: 10}}
          rightIcon={{name: 'send', onPress: () => startSearch()}}
        />
        <SpacedView h={5}>
          <Button
            type={'clear'}
            icon={{name: 'format-list-bulleted'}}
            onPress={openOutlineList}
          />
        </SpacedView>
        <SpacedView h={5}>
          <Avatar
            title={getInitialLetters(user.displayName)}
            rounded
            containerStyle={{backgroundColor: 'orange'}}
            onPress={showUserPopup}
          />
        </SpacedView>
      </View>
      <DocumentView
        ref={viewer}
        document={docPath}
        onLeadingNavButtonPressed={() => navigation.goBack()}
        longPressMenuEnabled={false}
        annotationMenuItems={[]}
        onDocumentLoaded={handleDocumentLoad}
        onAnnotationsSelected={handleSelectAnnotation}
        onAnnotationChanged={({action}) => console.log('action -- ', action)}
        onExportAnnotationCommand={handleExportAnnotCommand}
        currentUser={user?.displayName}
        hideToolbarsOnTap
        hideAnnotationToolbarSwitcher
        onToolChanged={({previousTool, tool}) => {
          console.log('Tool has been changed from', previousTool, 'to', tool);
        }}
        disabledElements={without(
          [
            'freeHandToolButton',
            'highlightToolButton',
            'freeTextToolButton',
            'outlineListButton',
          ],
          values(Config.Buttons),
        )}
        disabledTools={without(
          [
            'Pan',
            'AnnotationCreateFreeHand',
            'AnnotationCreateFreeHighlighter',
            'AnnotationCreateTextHighlight',
            'AnnotationCreateFreeText',
          ],
          values(Config.Tools),
        )}
      />
      <BottomSheet
        isVisible={contextOpen}
        onClose={closeContext}
        annotId={selectedAnnot?.id}
        deleteLoading={deleteLoading}
        onAnnotDelete={() => annotDelete()}>
        <AnnotationContext
          viewer={viewer}
          annot={selectedAnnot}
          onColorChange={onColorChange}
        />
      </BottomSheet>
      <Overlay isVisible={userPopupOpen} overlayStyle={styles.overlay}>
        <Icon
          name={'close'}
          containerStyle={{
            right: 10,
            top: 10,
            position: 'absolute',
            zIndex: 10000,
          }}
          size={20}
          onPress={() => setUserPopupOpen(false)}
        />
        <Text h4>Shared Notes</Text>
        <Text style={{color: colors.grey3, fontSize: 12}}>
          Users that shared notes in this document
        </Text>
        <SpacedView v>
          <ListItem containerStyle={{margin: 0}}>
            <Avatar
              title={getInitialLetters(user.displayName)}
              rounded
              containerStyle={{backgroundColor: 'orange'}}
            />
            <ListItem.Content>
              <ListItem.Title>{user.displayName}</ListItem.Title>
            </ListItem.Content>
          </ListItem>
        </SpacedView>
      </Overlay>
    </View>
  );`

**Comment by dcupidon** [comment]
As you correctly stated your code is hiding all the buttons and tools that you don't want. However, it is not hiding the top nav  bar itself. This causes the empty space that you are seeing. To hide this bar as well, set the `hideTopAppNavBar` to be true.

Let us know if this works.

**Comment by brerdem** [comment]
Thanks @dcupidon the empty space is gone after adding `hideTopAppNavBar`. However the annotation toolbar doesn't show up when I open the document. I need to click somewhere in the viewer once to display it (see the gif below). I also tried setting `hideToolbarsOnTap` to false just to check,  in that case annotation toolbar never gets displayed.

![capture](https://user-images.githubusercontent.com/778976/145455198-93377a6d-f703-44ec-80cc-3962026d33d0.gif)

**Comment by akwanpdf** [comment]
Thanks for the update! I noticed that you've disabled all the buttons in the bottom toolbar. Can you also add `bottomToolbarEnabled={false}` to your configuration? I've tested it out and it did the trick.

**Comment by brerdem** [comment]
Thank you very much @akwanpdf. It worked
