### ISSUE TITLE
Error while displaying documents offline

### ISSUE THREAD

**Issue by brerdem** [PDFTron/pdftron-react-native#434]
I'm getting an error when I try to display documents offline as shown in the screenshot. The document is loaded from local path and actually is displayed, but an error popup shows up over it. Additionally the annotation tools don't appear either

iOS 14.4
PDFTron 3.0.2

![image](https://user-images.githubusercontent.com/778976/145054842-de991600-d83b-41aa-8093-3d430199448a.png)

**Comment by sgong-pdftron** [comment]
Hi @brerdem would it be possible if you could send us this document so we can reproduce it on our end? Thanks.

**Comment by brerdem** [comment]
Sure @sgong-pdftron 
You can download it here: [https://firebasestorage.googleapis.com/v0/b/ebookbox-bvs.appspot.com/o/docs%2F67062_1_d.pdf?alt=media&token=5c5cc510-93ba-4170-97d2-854cc9354c38](https://firebasestorage.googleapis.com/v0/b/ebookbox-bvs.appspot.com/o/docs%2F67062_1_d.pdf?alt=media&token=5c5cc510-93ba-4170-97d2-854cc9354c38 )

By the way, as a side note, I'm using Firebase Firestore for annotation data and it seems fine, I can get all datas and I use` react-native-fetch-blob ` to fetch the document from storage.

**Comment by dcupidon** [comment]
I downloaded the file to my MacBook and referenced the local path in my example app. My simulator ran the app without the alert popping up. Is it possible for you to show you the files are retrieved from local storage?

**Comment by brerdem** [comment]
@dcupidon did you try to open it up offline? You can't do it with the simulator as far as I know. You need a real device and cut the connection then try to open up from local path.

here is the snippet of code I'm using. Maybe it gives you an idea. Basically it downloads the file from firebase storage to phone's local storage and later I'm trying to open the doc from this local path
```
 const downloadDoc = async () => {
    const res = await RNFetchBlob.config({
      fileCache: true,
      appendExt: 'pdf',
    }).fetch('GET', contextDoc.url);

    if (res.path()) {
      dispatch(addToDownloads({id: contextDoc.id, path: res.path()}));
      console.log('document downloaded');
    }
  };

```
Interestingly as I said before the document opens up actually and everything else apart from this alert seems fine. Is there a method to disable/ignore the alerts on PDFTron library? Maybe I can just ignore it and I'll be fine

**Comment by dcupidon** [comment]
Could you try the following snippet:
```js
RNPdftron.initialize(licenseKey);
RNPdftron.enableJavaScript(false);
```
If that doesn't work, please send a sample project for us to test.

**Comment by brerdem** [comment]
Sorry for late reply @dcupidon. Unfortunately disabling JavaScript didn't work. I added you as a collaborator to the minimal reproducible demo of the project. Please let me know if you need anything else

To test it out, you'll need a real iOS device of course. When you open the app you'll see a single document in My Library section, press little 3 dots icon below the thumbnail and select Download. Then turn off the internet of your device and select the document. You'll see the error shows up but also the document itself behind

Thanks!

**Comment by sgong-pdftron** [comment]
Hi @brerdem Dominic is no longer with us. Could you please submit a ticket at https://www.pdftron.com/form/request/ so someone from the iOS team can help you out? Typically for customers, please submit bug report instead of on GitHub for better assistance. Thanks.

**Comment by sgong-pdftron** [comment]
closing in favor of ticketing system https://www.pdftron.com/form/request/
