### ISSUE TITLE
Problems with translations

### ISSUE THREAD

**Issue by FranckCN** [PDFTron/pdftron-react-native#438]
Hello 👋,

We develop an app with PDFTron in React-Native and it seems we get some problems with translations.

We have no translation on iOS and Android is partialy translated.

Is it normal ? If yes, for Android, maybe we can help you by adding some missing translations :)

**Comment by sgong-pdftron** [comment]
Hi @FranckCN may I ask what language(s) you are looking for?

**Comment by FranckCN** [comment]
Hi, thank you for answering that fast ! :)

Firstly, maybe we found the issue with iOS, I'll update you as soon as we can test it.

We are looking for french.

**Comment by sgong-pdftron** [comment]
Please reopen if there is any further issues.
