### ISSUE TITLE
Android Export Path issue

### ISSUE THREAD

**Issue by talhamuhammadashraf** [PDFTron/pdftron-react-native#490]
can not find the downloaded copy when save using "save a copy"

**Comment by sgong-pdftron** [comment]
You can obtain path for any file using: https://github.com/PDFTron/pdftron-react-native/blob/master/API.md#getdocumentpath

**Comment by talhaashraf-10p** [comment]
@sgong-pdftron  can i pass a certain path for android to be saved

**Comment by sgong-pdftron** [comment]
@talhaashraf-10p that's not supported at the moment, however you can use React Native IO utilities to copy the saved document to your desired location, note this applies to the "save a copy" options. If you are asking about general saving, you can pass in the document from the desired path and it will get saved back to the original location.
