### ISSUE TITLE
Building ios fails with error in RNTPTDocumentView.m

### ISSUE THREAD

**Issue by dominicrico** [PDFTron/pdftron-react-native#5]
Hi,

I try to get PDFTron running in my react-native project. I installed it with cocoaPods and yarn but if I want to run the project the build fails with following error.

File: RNTPTDocumentView.m 
Line: 63

```
BOOL success = [_documentController openDocumentWithURL:fileURL error:&error];                          

//ERROR No visible @interface for 'PTTabbedDocumentViewController' declares the selector 'openDocumentWithURL:error:'
```

I'm using the xcworkspace project generated by cocoa and can't get it to run. 

Any help would be appreciated.

**Comment by sgong-pdftron** [comment]
@dominicrico 
This has been fixed with commit https://github.com/PDFTron/pdftron-react-native/commit/b05e7edf4ef073b8eb1ccda10c428235a60c93ab

Could you update and try again? Thanks.

**Comment by dluco-pdftron** [comment]
Hi @dominicrico 
You can run `npm install` to get the latest update with the fix @sgong-pdftron mentioned.
Please let us know how this works for you. Thanks!

**Comment by sgong-pdftron** [comment]
Closed as issue should be resolved. Re-open if the issue still persist. Thanks.
