### ISSUE TITLE
[Android] Functionality in RNPdfViewCtrlTabFragment not supported in collab viewer

### ISSUE THREAD

**Issue by brandenfung2** [PDFTron/pdftron-react-native#500]
**Describe the bug**

- Functionality implemented in RNPdfViewCtrlTabFragment such as imageStamperSelected and imageSignatureSelected needs to be added to collab viewer

**Expected behavior**

**Screenshots**

**Platform/Device Information (please complete the following information if applicable):**
 - Platform:Android
 
**Additional context**

**Comment by sgong-pdftron** [comment]
We are closing down issues section in favor of official Apryse support channel, please report issues through our official channel at https://apryse.com/support
