### ISSUE TITLE
unable to import multiple annotation in android (iOS is working fine)

### ISSUE THREAD

**Issue by somasekharkakarla** [PDFTron/pdftron-react-native#502]
@sgong-pdftron  While I am importing annotations using method `this.docView.importAnnotations` in a for loop, only the last item is able to view on PDF but in iOS it working fine

**Comment by somasekharkakarla** [comment]
I am able to resolve this by editing android library in views > DocumentView.class at line 3043 with `pdfDoc.fdfMerge(fdfDoc);` instead of `pdfDoc.fdfUpdate(fdfDoc);`

**Comment by sgong-pdftron** [comment]
@somasekharkakarla import annotation is designed to handle a snapshot of all annotations in a single XFDF String, for snapshot of single annotation, importAnnotationCommand is what you should really use, which will indicate either annotation is added/modified/deleted.

**Comment by damianimashaun** [comment]
> @somasekharkakarla import annotation is designed to handle a snapshot of all annotations in a single XFDF String, for snapshot of single annotation, importAnnotationCommand is what you should really use, which will indicate either annotation is added/modified/deleted.

hey @sgong-pdftron this is not the case, I had the same issue as @somasekharkakarla and his solution worked for me

**Comment by sgong-pdftron** [comment]
Thanks for the feedback, sounds to me there should be 2 variation of `importAnnotations`, where a param can be passed in to indicate whether to replace existing annotations:
so `importAnnotations(true)` will replace -> default and same with current behaviour
and `importAnnotations(false)` will combine -> allow multiple XFDF to be merged

That should work for both cases

**Comment by somasekharkakarla** [comment]
@sgong-pdftron I didn't use this methods` importAnnotations(true)` at all. I run both android and ios at once iOS is showing all the annotations which I added but Android is showing only the last one. I think the update method is only updating and replacing with the latest annotation. The merge function is merging all annotations.

**Comment by sgong-pdftron** [comment]
@somasekharkakarla that is my proposal, not implemented yet, the difference between Update and Merge is Merge will create duplicates, so for example if your server has a snapshot of the whole document, you cannot use merge as that will produce 2 sets of the same annotations. Update is used in that case to replace the entire annotation snapshot of the document. In any case I will add the param to handle both cases
