### ISSUE TITLE
Feature request: Real time collaboration

### ISSUE THREAD

**Issue by sonlexqt** [PDFTron/pdftron-react-native#51]
From PDFTron documentation, we can see the guides for real time collaboration on [Android](https://www.pdftron.com/documentation/android/guides/collab/overview-a/) and [iOS](https://www.pdftron.com/documentation/ios/guides/collab/overview-i/). How can we implement such feature using pdftron-react-native ?

**Comment by sgong-pdftron** [comment]
@sonlexqt what timeline are you looking at for collaboration support? Thanks!

**Comment by sgong-pdftron** [comment]
closed by https://github.com/PDFTron/pdftron-react-native/pull/58
