### ISSUE TITLE
Missing annotation tools

### ISSUE THREAD

**Issue by damianimashaun** [PDFTron/pdftron-react-native#512]
Hello, I cannot see the Callout tool in iOS, 
also the Caret tool is missing in both iOS and android, 
is this intentional ?

**Comment by sgong-pdftron** [comment]
Hi @damianimashaun on iOS, you can see the Callout tool in the long-press menu, under the "Shapes..." submenu, (last item in the shapes menu, have to hit the right arrow a few times to get to it)

Caret tool is not supported on mobile platforms.
