### ISSUE TITLE
Trigger function with event when redo/undo is pressed

### ISSUE THREAD

**Issue by damianimashaun** [PDFTron/pdftron-react-native#514]
Hello,
Currently when undo or redo is pressed there is no function triggered with the event.
onUndoRedoStateChanged is called with no event.
In a scenario where the app has a db source to save individual annotations, is there any way to to respond to the undo/redo buttons pressed, with the accurate event , so I can either update the annotation in the db or delete it ?

**Comment by sgong-pdftron** [comment]
Hi, your use case sound to me that you need to use collaboration mode and use https://github.com/PDFTron/pdftron-react-native/blob/master/API.md#onexportannotationcommand instead to get snapshot changes in the form of XFDF. Could you give that a try instead?
