### ISSUE TITLE
TypeScript support?

### ISSUE THREAD

**Issue by velsa** [PDFTron/pdftron-react-native#52]
Trying to build a new react native app using `expo init` and typescript template. 
And obviously get this error:
```
Could not find a declaration file for module 'react-native-pdftron'. 
'/Users/vels/dev/TKCConnect/node_modules/react-native-pdftron/index.js' implicitly 
has an 'any' type.
Try `npm install @types/react-native-pdftron` if it exists or add a new declaration (.d.ts) 
file containing `declare module 'react-native-pdftron';`ts(7016)
```

As far as I understand, there is no `.d.ts` file for this project.
Any plans on creating/adding it?
Any ideas on how I can still use your wrapper in my typescript app?

Sorry for the newbie questions :)

**Comment by sgong-pdftron** [comment]
@velsa TypeScript is not currently supported, what timeline are you looking at for TypeScript support?

**Comment by velsa** [comment]
The timeline for the app I'm working on is to have a first working alfa in 2-3 months.
But actually I was able to compile the app by adding a `types.d.ts` file with a line `declare module '*';`

But the issue now is that I get 
```
null is not an object (evaluating '_reactNativePdftron.RNPdftron.initialize')
```

when I try to run the example app.
Here's the code: https://gist.github.com/velsa/4a664cdb40cd3bbece49de03887c5ccf

**Comment by sgong-pdftron** [comment]
@velsa we do have other customer that are able to build and run with typescript, can you post your typescript config? Thanks.

**Comment by sgong-pdftron** [comment]
Typescript is fully supported, see new sample project: https://github.com/PDFTron/pdftron-react-and-react-native-sample
