### ISSUE TITLE
Dark mode doesn't work on tools bar, settings screen, etc

### ISSUE THREAD

**Issue by misha-pavlov** [PDFTron/pdftron-react-native#527]
When user select color mode as 'Dark Mode' this mode will be only on pdf page, but tools bar, settings, etc will be in 'Light Mode'.

![Simulator Screen Shot - iPhone 12 - 2022-03-21 at 13 28 59](https://user-images.githubusercontent.com/79836377/159340015-4ae3619b-cfb2-421f-affc-02cb6a843e17.png)

**Comment by JamesTron** [comment]
Hi Misha,

The view setting's colour mode affects how the PDF is rendered, not the UI of the app. The UI will conform to the device's light/dark mode setting. This way you can have your device in dark mode, but still see the PDF rendered normally.

James
