### ISSUE TITLE
Customize "Write your comment" placeholder while adding a reply

### ISSUE THREAD

**Issue by damianimashaun** [PDFTron/pdftron-react-native#529]
<img width="315" alt="image" src="https://user-images.githubusercontent.com/49630919/159478900-84d3d124-379d-40f5-9d73-a816f57b2271.png">

In Screenshot above, though the text box is actually to reply to a comment it says "Write your comment".
Please can you add a prop to customise this ?

**Comment by sgong-pdftron** [comment]
Hi @damianimashaun, yes you can edit this string, you'll want to include the following in "src/main/res/values/strings.xml" of your android application:

<string name="reply_editor_write_hint">Add your desired string here</string>

Thanks.

**Comment by damianimashaun** [comment]
@sgong-pdftron Please what's the equivalent for this on iOS ?
