### ISSUE TITLE
Default status of new annotation should be 'None' instead of previously selected status

### ISSUE THREAD

**Issue by damianimashaun** [PDFTron/pdftron-react-native#530]
In the video below,  I set the status of an annotation, then I create a new annotation, note the status of the new annotation;

https://user-images.githubusercontent.com/49630919/159480942-45c823c8-ef12-4d50-b2b7-01973e511ebf.mp4

Is there a way to resolve this ? I don't see any prop for changing this behaviour

**Comment by sgong-pdftron** [comment]
We are closing down issues section in favor of official Apryse support channel here, please report issues through our official channel at https://apryse.com/support
