### ISSUE TITLE
Cannot edit initial comment of some annotations

### ISSUE THREAD

**Issue by damianimashaun** [PDFTron/pdftron-react-native#531]
Hi, unlike the notes and text annotations in which the annotation is the First comment, it is not possible to change the Initial comment of a some annotation, like the shape annotations or pencil drawing for example.

After creating the annotation the first comment is left blank and can be edited only on Web.

![image](https://user-images.githubusercontent.com/49630919/159484425-91012a13-1895-486a-890a-a4ac4efcaf14.png)

**Comment by ama-pdftron** [comment]
@damianimashaun 
Android has completed this change and should be available on the latest React Native version. Please give this a try and let us know if it works for you.

https://user-images.githubusercontent.com/83238520/165809910-9110b5f9-4d92-40e6-a34c-a243cd7ea98c.mov
