### ISSUE TITLE
Can't add file attachment

### ISSUE THREAD

**Issue by misha-pavlov** [PDFTron/pdftron-react-native#533]
For example attach image will show as just a text, not as image

**Comment by sgong-pdftron** [comment]
@misha-pavlov do you have a video and/or a sample project showing what you mean? Thanks.

**Comment by ama-pdftron** [comment]
@misha-pavlov 

Thanks for sending the video. What's the expectation after reaching the file attachment dialog? Which actions would you expect to be available? For example, would you expect to see an option to extract the file attachment?

**Comment by misha-pavlov** [comment]
I think must be onPress event which give possibility download file. I mean that user press on attached file and download this file.

**Comment by ama-pdftron** [comment]
@misha-pavlov 
We noticed in your video that the quick menu did not show the Open Attachments option, could you provide a sample code that shows which settings you've enabled or disabled? For reference tapping on the attachment annotation should give you an option to open like this:
![Screenshot_1648835598](https://user-images.githubusercontent.com/83238520/161316555-a107950f-2654-41a6-99cf-a129faa88326.png)

**Comment by ama-pdftron** [comment]
@misha-pavlov 

Can you enable the setting for openAttachments by uncommenting this line?
```
// hide open attachment on mobile
// PDFTronConfig.AnnotationMenu.openAttachment
```

May we ask why this line needed to be commented out in the first place?

**Comment by misha-pavlov** [comment]
I commented this line because we don't want the user to be able to open the attached file.
The only action for attached files should be 'download file'

**Comment by sgong-pdftron** [comment]
@misha-pavlov understood. This would be a feature request as currently we only support open directly. Could you please submit a feature request ticket through our official ticket system here: https://www.pdftron.com/support/. Thank you!
