### ISSUE TITLE
Annotation text not visible in dark mode (text is light)

### ISSUE THREAD

**Issue by misha-pavlov** [PDFTron/pdftron-react-native#534]
When user have dark theme on phone and DocumentView have props followSystemDarkMode={false} annotate note will have a light text color in first open.
![Знімок екрана 2022-03-22 о 16 12 20](https://user-images.githubusercontent.com/79836377/159576801-7647e2e7-3c08-4186-9056-025da6b0ea91.png)

**Comment by JamieDass** [comment]
Hi @misha-pavlov,

Thank you for reporting this, we are investigating and will let you know what we find.
