### ISSUE TITLE
Anyway to enable/disable onExportAnnotationCommand trigger for setPropertiesForAnnotation

### ISSUE THREAD

**Issue by somasekharkakarla** [PDFTron/pdftron-react-native#542]
Hi @sgong-pdftron,
Is there any way to enable/disable onExportAnnotationCommand trigger?
When i use **setPropertiesForAnnotation** to set custom data for after annotation is added onExportAnnotationCommand > modify is called.

**Scenario:** 
When annotation is created, the request call will add annotation to the server and the server will reply with custom data for that annotation. while adding the custom data using setPropertiesForAnnotation the onExportAnnotationCommand > modify is called. which leads to recursive request calls.

Can you please add enable/disable onExportAnnotationCommand trigger property to  setPropertiesForAnnotation?

**Comment by sgong-pdftron** [comment]
@somasekharkakarla I believe you'll have to keep track of that yourself. I would recommend a map on your end which you will add to "ignore" list, ignore the call for any item in the ignore list, then clear them out after consumed. Could you give it a try?

**Comment by somasekharkakarla** [comment]
@sgong-pdftron at present i am doing same. Just i want you to make it more easy for the users which can help other users in other scenario's. It will be simple for us to add trigger param to the setPropertiesForAnnotation instead maintaining list.

**Comment by sgong-pdftron** [comment]
Typically server DB should be the ground truth and client should send server every information it got. So in this case, your server side should be able to know not to further send out repeated information to the client. Thanks.
