### ISSUE TITLE
Support for Expo config plugin

### ISSUE THREAD

**Issue by cwhfa** [PDFTron/pdftron-react-native#550]
**Describe the bug**
Right now manual changes are needed to make Android and iOS builds work (The [Android](https://github.com/PDFTron/pdftron-react-native#android) and [iOS](https://github.com/PDFTron/pdftron-react-native#ios) part of the readme) when using a [Expo Development project](https://docs.expo.dev/development/getting-started/)

Would it be possible for you to make a [config plugin](https://docs.expo.dev/guides/config-plugins/#creating-a-plugin) so I dont have to manually insert the needed changes?

**Comment by sgong-pdftron** [comment]
We are closing down issues section in favor of official Apryse support channel here, please report issues through our official channel at https://apryse.com/support
