### ISSUE TITLE
onLoadComplete & onDocumentLoaded only fire when open button click

### ISSUE THREAD

**Issue by abdoerrahiem** [PDFTron/pdftron-react-native#576]
I got some issues with the library,
When I want to export the file, the success alert only shows when the file is pdf (docx, png, etc don't show).
And onLoadComplete/onDocumentLoaded only fire when OPEN button tapped, but if I tap OK button they don't fire.

**Comment by sgong-pdftron** [comment]
@abdoerrahiem could you please provide screenshots or videos so we can better assist you? Thanks.
