### ISSUE TITLE
Android fails to build after upgrading this package (Could not HEAD exoplayer)

### ISSUE THREAD

**Issue by adam-lynch** [PDFTron/pdftron-react-native#580]
**Describe the bug**

After upgrading this package, building our Android app in Android Studio fails with the following error:

```
Could not HEAD 'https://pdftron-maven.s3.amazonaws.com/snapshot/com/google/android/exoplayer/exoplayer-core/2.11.4/exoplayer-core-2.11.4.pom'. Received status code 403 from server: Forbidden
Disable Gradle 'offline mode' and sync project
```

**Steps to Reproduce the Problem**

1. Upgrade from commit https://github.com/PDFTron/pdftron-react-native/commit/a00d39a1c50a8c538d49e2b0e9f4512d71662ed8 to `@pdftron/react-native-pdf@3.0.2-beta.112` or even `@pdftron/react-native-pdf@3.0.2-beta.64`.
2. Clean.
3. Sync.
4. Build.

**Expected behavior**

The build should run successfully.

**Screenshots**

N/A

**Platform/Device Information (please complete the following information if applicable):**
 - Platform: Android
 - Device: N/A
 - OS: N/A

**Additional context**

Forgive me, this is a strange one.

We were previously installing directly from GitHub, specifically this comment: https://github.com/PDFTron/pdftron-react-native/commit/a00d39a1c50a8c538d49e2b0e9f4512d71662ed8. I assume this is because we needed a fix that wasn't published yet at the time.

I needed to upgrade the package to at least `@pdftron/react-native-pdf@3.0.2-beta.64` to get https://github.com/PDFTron/pdftron-react-native/issues/502.

We also depend on `react-native-track-player` and `expo-av`. Both depend on exoplayer too (two different versions). I came across https://github.com/doublesymmetry/react-native-track-player/issues/1235 and tried all workarounds plus the `rc` releases, but it still fails.

Oh and to be clear, this breaks on a pull-request I made that just adds `@pdftron/react-native-pdf@3.0.2-beta.112` and removes `"react-native-pdftron": "github:PDFTron/pdftron-react-native#a00d39a1c50a8c538d49e2b0e9f4512d71662ed8"`. Master builds fine.

**Comment by arekm213** [comment]
Hey, i created a sample project for you so you could take a look on that issue
https://github.com/arekm213/pdftronrepro
As @adam-lynch mentioned going back to `"react-native-pdftron": "github:PDFTron/pdftron-react-native#a00d39a1c50a8c538d49e2b0e9f4512d71662ed8"` makes us able to build project

**Comment by terryyoon-pdftron** [comment]
Thank you for the sample project, we were able to take a look at the issue and track down the [commit](https://github.com/PDFTron/pdftron-react-native/pull/488) that contributed to it.

Essentially, the issue originates from the fact that the versions of some packages that your dependencies depend on are not present in the Maven Central repository. As we have removed JCenter in this PR, this caused your project to fail.

As a temporary workaround, you could add back those missing packages from JCenter in your `android/build.gradle` file:

```
allprojects {
    repositories {
        ...
        jcenter() {
            content {
                includeGroup("com.google.android.exoplayer")
                includeModule("com.yqritc", "android-scalablevideoview")
            }
        }
        ...
    }
}
```

**Comment by adam-lynch** [comment]
Thank you!
