### ISSUE TITLE
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.

### ISSUE THREAD

**Issue by Sanaullahbugti** [PDFTron/pdftron-react-native#588]
npm ERR! @pdftron/react-native-pdf@3.0.2-beta.118 postinstall: `python3 scripts/newPodspecMessage.py`
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
![image](https://user-images.githubusercontent.com/39256766/179728696-d06883ca-a62e-401b-9c4a-33935c01ab0c.png)

**Comment by terryyoon-pdftron** [comment]
Hey there, please make sure Python is installed on your machine by running `python3` on your console.

**Comment by Sanaullahbugti** [comment]
Hey @terryyoon-pdftron  Thanks for the reply. The above issue is resolved now I am getting following issue 
![image](https://user-images.githubusercontent.com/39256766/180449760-d137a9ea-c98e-46eb-ad6c-4265ad698899.png)
