### ISSUE TITLE
ViewPropTypes will be removed from React Native. Migrate to ViewPropTypes exported from 'deprecated-react-native-prop-types'. 

### ISSUE THREAD

**Issue by Sanaullahbugti** [PDFTron/pdftron-react-native#590]
ViewPropTypes will be removed from React Native. Migrate to ViewPropTypes exported from 'deprecated-react-native-prop-types'.

**Comment by terryyoon-pdftron** [comment]
Hey there, https://github.com/PDFTron/pdftron-react-native/pull/591 was just merged that will fix this issue. Could you pull and try again?

**Comment by Sanaullahbugti** [comment]
That works
