### ISSUE TITLE
Builds fails when new PDFNet version is available

### ISSUE THREAD

**Issue by henninghall** [PDFTron/pdftron-react-native#597]
**Describe the bug**

When a new version of PDFNet is available, a build that previously succeeded now fails. This happens because PDFNet podspec points towards https://pdftron.com/downloads/ios/react-native/latest.podspec which changes sometimes.

```rb
target 'MyApp' do
    # ...
    pod 'PDFNet', podspec: 'https://pdftron.com/downloads/ios/react-native/latest.podspec'
    # ...
end
```

**Expected behavior**
I expect the locked dependencies to be locked into a specific version. When updating PDFTron I expect the PDFNet version to be updated to the latest version you support. 

**Screenshots**
![Screenshot 2022-08-23 at 10 47 29](https://user-images.githubusercontent.com/1652607/186116913-651971d4-3d6d-46c8-822f-27b5fb7bb9d2.png)

**Stacktrace**

<code>
[!] CocoaPods could not find compatible versions for pod "PDFNet":
  In snapshot (Podfile.lock):
    PDFNet (from `https://pdftron.com/downloads/ios/react-native/latest.podspec`)
  In Podfile:
    PDFNet (from `https://pdftron.com/downloads/ios/react-native/latest.podspec`)
It seems like you've changed the version of the dependency `PDFNet` and it differs from the version stored in `Pods/Local Podspecs`.
You should run `pod update PDFNet --no-repo-update` to apply changes made locally.
</code>
<br/>

## Questions
 
 1. Is there a way around this? 
 2. Would you consider locking down the PDFNet version instead of pointing to a moving target? 
 
 Thanks!

**Comment by dluco** [comment]
Hi there,
We do offer versioned CocoaPod podspecs for each release if you would prefer: [https://www.pdftron.com/documentation/ios/get-started/integration/cocoapods/#option-2](https://www.pdftron.com/documentation/ios/get-started/integration/cocoapods/#option-2)

eg. https://www.pdftron.com/downloads/ios/cocoapods/xcframeworks/pdfnet/9.3.0.80119.podspec

When you are building your project and running into the pod version issue, what command are you running?

I think the `Pods/Local Podspecs` cache in your project should have a local copy of the PDFNet podspec that matches the version in your Podfile.lock file. You may need to consult the CocoaPods documentation on how this is supposed to work though.

**Comment by henninghall** [comment]
Thanks for your answer! 

>We do offer versioned CocoaPod podspecs for each release if you would prefer: https://www.pdftron.com/documentation/ios/get-started/integration/cocoapods/#option-2

Oh that's nice! That would work better, but how do we know when to bump that version? When you release a new `pdftron-react-native` version, can we assume the latest PDFNet version works with that?

>When you are building your project and running into the pod version issue, what command are you running?
`pod install`

When this error happens it was possible to bump version by running `pod update PDFNet --no-repo-update` which was suggested in the error message. This doesn't really help though, maybe we don't want to upgrade at that time, or this could happen on CI (which was our original problem). 

>I think the Pods/Local Podspecs cache in your project should have a local copy of the PDFNet podspec that matches the version in your Podfile.lock file. You may need to consult the CocoaPods documentation on how this is supposed to work though.

I definitely don't have that much knowledge about CocaoPods so that could definitely be the case 😅 But that still wouldn't help for new developers / CI if I understand correctly.


**Suggestion**
I've researched this a bit and found that some projects, including react-native project itself, seem to solve this issue by having multiple .podspec files in the same project. In your case it would mean adding a `PDFNet.podspec` next to the `RNPdftron.podspec`. That would be very convenient for us who uses the lib since we don't have to add this line 

```rb
pod 'PDFNet', podspec: 'https://pdftron.com/downloads/ios/react-native/latest.podspec'
```
to our Podfile, we won't have the issue I ran into here and you get the control of pinning a specific PDFNet version to a specific `pdftron-react-native` version.

It would mean that you have to bump that version when you make a new release. I don't know how your workflow works and if this would be an option for you?

**Comment by hamzaawais96** [comment]
@henninghall did you find a way to resolve this issue?

**Comment by henninghall** [comment]
A workaround until this is solved is to pin the version to PDFNet in the Podfile instead of using "latest". 

You just need to remember to update both the Podfile and package.json when you upgrade pdfton later.

**Comment by hamzaawais96** [comment]
Yeah, that's what I was thinking of. But I actually don't want to update the files manually.
Thanks for your quick reply.

**Comment by henninghall** [comment]
Yes that's unfortunate, I guess we will have to wait for Pdftron to fix it. 

Maybe some kind of postinstall script could work too, downloading the latest podspec, checking the version and updating Podfile.

**Comment by sgong-pdftron** [comment]
We are closing down issues section in favor of official Apryse support channel here, please report issues through our official channel at https://apryse.com/support
