### ISSUE TITLE
Can't use Base64 PDF loading

### ISSUE THREAD

**Issue by JQQ-GIT** [PDFTron/pdftron-react-native#602]
**Describe the bug**

**Steps to Reproduce the Problem**

**Expected behavior**

**Screenshots**

**Platform/Device Information (please complete the following information if applicable):**
 - Platform:[e.g. iOS or Android]
 - Device: [e.g. iPhone6, Google Pixel 4]
 - OS: [e.g. iOS8.1, Android Nougat]

**Additional context**

**Comment by darrenchann** [comment]
Hi @JQQ-GIT 

Would you be able to provide some video demonstrating this error as well as some sample code that could help us better understand this issue? 

Also, what device and OS are you using as those fields didn't seem to be filled out.
