### ISSUE TITLE
White flickering (reload?) when running `importAnnotations`

### ISSUE THREAD

**Issue by henninghall** [PDFTron/pdftron-react-native#607]
**Describe the bug**

When calling `importAnnotations` a "white flickering" or some kind of reload appears before the annotations are imported (see screencap below). It happens on both Android and iOS. 

On iOS the flickering can be avoided by selecting any annotation before calling `importAnnotations` (see screencap). 

1. Do you have any idea why this happens? 
2. Is there a way around it? 

**Attempts**
- I have tried to dig through the source code to tried to find some clues but I haven't found anyting yet.
- Tried to set the second parameter replace to `false`. 

https://user-images.githubusercontent.com/1652607/189834132-2f8c2b4c-8861-4b6c-9bd4-9a0186c55e70.mov

**Expected behavior**

No white flickering / reload when calling `importAnnotations`.

**Platform/Device Information**
 - Platform: iOS and Android 
 - Device: All seem affected (tested on iPhone13)
 - OS: All seem affected (tested on iOS 14/15, android sdk 29/30)

**Comment by darrenchann** [comment]
Hi @henninghall 

`importAnnotations` is not meant for adding annotations based on the video you've provided. The purpose of the API is to import all annotations from a remote location to the viewer when the viewer first starts up. 

Is there a particular use case / user story that you're trying to achieve? If so, there may be a better API that we can recommend to you that could better accomplish what you're looking for that doesn't have the flickering UI occurring.

**Comment by henninghall** [comment]
Okay, yeah I would like to add a annotation on the fly without using the built-in GUI for this, is that possible? 

If not, do you have any idea about why the white flickering/reload happens? (I might do some deeper debugging to find a workaround since it seems technically possible to avoid this in this particular situation, at least on iOS)

**Comment by darrenchann** [comment]
The flickering occurs when `update` gets called after you use importAnnotations. 

Unfortunately, we currently don't support adding annotations programmatically on the fly as you may need to dive into native code to see if you can implement this into your app.

**Comment by sgong-pdftron** [comment]
We are closing down issues section in favor of official Apryse support channel here, please report issues through our official channel at https://apryse.com/support
