### ISSUE TITLE
No option to add an annotation programmatically

### ISSUE THREAD

**Issue by shessafridi** [PDFTron/pdftron-react-native#618]
**Describe the bug**
No option to add an annotation programmatically.

There is a method to delete an annotation but not for creating an annotation, I have the text selection coords now I want to create a `Annotations.TextHighlightAnnotation()` like I'm doing on the web but there is no option for it in this library.

**Expected behavior**
There should be a `createAnnotation` method to programmatically create annotations.

**Comment by darrenchann** [comment]
Hi @shessafridi 

Please submit a ticket through our support desk for any feature requests:
https://www.pdftron.com/support/
