### ISSUE TITLE
findText only return one match even if there are multiple

### ISSUE THREAD

**Issue by sryorch** [PDFTron/pdftron-react-native#641]
Currently DocumentViewer.findText only return 1 match on the onTextSearchResult event, will be good if we can get every match case on the PDF.

**Comment by Tyler-Gordon** [comment]
Hello sryorch,

Can you send exact steps to reproduce this issue?

**Comment by sgong-pdftron** [comment]
We are closing down issues section in favor of official Apryse support channel here, please report issues through our official channel at https://apryse.com/support
