### ISSUE TITLE
project ':pdftron_react-native-pdf' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.0

### ISSUE THREAD

**Issue by Etaliya** [PDFTron/pdftron-react-native#642]
![Screenshot 2023-01-31 at 1 48 50 PM](https://user-images.githubusercontent.com/54949248/215705092-1762c168-c3ec-4c89-9e82-ad3507a04701.png)

System:
    OS: macOS 12.5
    CPU: (6) x64 Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
    Memory: 161.25 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.0 - ~/.nvm/versions/node/v16.19.0/bin/npm
    Watchman: 2022.12.26.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9477386
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.1 => 0.71.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by Tyler-Gordon** [comment]
Hello Etaliya,

Can you please provide steps on how I can reproduce this issue?

**Comment by Raffay20** [comment]
Hello Guys ,
Im also encountered with same error

**Comment by Tyler-Gordon** [comment]
How can I reproduce this issue?

**Comment by Raffay20** [comment]
@Tyler-Gordon I try to Setup Pdf-tron on react native cli project. its give me this error but now i'm running it on Expo cli its working fine.

**Comment by Raffay20** [comment]
@Tyler-Gordon  before i try to add pdftron library following this https://github.com/PDFTron/pdftron-react-native documentation and i encountered with this error.

**Comment by sacmii** [comment]
Editing
 **node_modules/react-native-pdftron/android/build.gradle** 
**ext.kotlinVersion** to **'1.6.20'**
fixed problems temporarily

**Comment by sgong-pdftron** [comment]
closed by https://github.com/PDFTron/pdftron-react-native/pull/651
