### ISSUE TITLE
[iOS] App get crash when we use draw toolbar

### ISSUE THREAD

**Issue by hamzaawais96** [PDFTron/pdftron-react-native#650]
**Describe the bug**
Whenever we choose Draw Toolbar and try to draw some shapes e.g `Polyline, polygon, line, arrow, and polygon cloud`, the iOS app crashes with the following error. 

`Terminating app due to uncaught exception 'NSGenericException', reason: 'Unable to activate constraint with anchors <NSLayoutXAxisAnchor:0x280b0ad40 "PTResizeWidgetView:0x157e12aa0.centerX"> and <NSLayoutXAxisAnchor:0x280b0b380 "UIView:0x157e15f40.right"> because they have no common ancestor.  Does the constraint or its anchors reference items in different view hierarchies?  That's illegal.`

**Steps to Reproduce the Problem**
1. Open any document using the `DocumentView` component
2. Select the Draw toolbar and try to draw a polygon or any other shape (except circle). The app will get crashed. You will also face the same crash when you click on "complete annotation" button.

**Expected behavior**
App should  not get crashed on using Draw toolbar of `DocumentView`.

**Platform/Device Information (please complete the following information if applicable):**
 - Platform: iOS

**Comment by sgong-pdftron** [comment]
@hamzaawais96 please report issues through our official channel at https://apryse.com/support
