### ISSUE TITLE
[!] CocoaPods could not find compatible versions for pod "PDFNet":

### ISSUE THREAD

**Issue by Rana-Muhammad-Amir** [PDFTron/pdftron-react-native#77]
[!] CocoaPods could not find compatible versions for pod "PDFNet":
  In Podfile:
    PDFNet (from `https://www.pdftron.com/downloads/ios/cocoapods/pdfnet/latest.podspec`)

    RNPdftron (from `../node_modules/react-native-pdftron`) was resolved to 1.0.0, which depends on
      PDFNet

Specs satisfying the `PDFNet (from `https://www.pdftron.com/downloads/ios/cocoapods/pdfnet/latest.podspec`), PDFNet` dependency were found, but they required a higher minimum deployment target.

the minimum target set is:
platform :ios, '9.0'

facing this issue while running 'pod install' 
please suggest solution

**Comment by dluco-pdftron** [comment]
Hi @Rana-Muhammad-Amir, thanks for letting us know about this issue!
To install the PDFNet CocoaPod, you'll need to change your minimum target to iOS 11 in your `Podfile`:
```
platform :ios, '11.0'
```
and then run `pod install` to install the dependency.
