### ISSUE TITLE
Merge custom-headers-fix to master branch ?

### ISSUE THREAD

**Issue by sonlexqt** [PDFTron/pdftron-react-native#92]
Hi, I tried the `custom-headers-fix` and the issue of not sending the request headers on iOS has been fixed. When can you merge this branch to `master` ?

**Comment by dluco-pdftron** [comment]
Hi @sonlexqt,
We can merge the `custom-header-fix` when the next official version of the PDFTron iOS SDK is released, likely next week. The branch relies on fixes/features currently only available in nightly builds and so can't be merged yet.

**Comment by sonlexqt** [comment]
@dluco-pdftron great, thanks for the info!
